// HSK 3.0 Level 1 Vocabulary Database
// Contains approximately 500 words required for HSK 3.0 Level 1

const HSK_VOCABULARY = [
    // Pronouns
    { id: 1, chinese: "我", pinyin: "wǒ", english: "I, me" },
    { id: 2, chinese: "你", pinyin: "nǐ", english: "you" },
    { id: 3, chinese: "他", pinyin: "tā", english: "he, him" },
    { id: 4, chinese: "她", pinyin: "tā", english: "she, her" },
    { id: 5, chinese: "它", pinyin: "tā", english: "it" },
    { id: 6, chinese: "我们", pinyin: "wǒmen", english: "we, us" },
    { id: 7, chinese: "你们", pinyin: "nǐmen", english: "you (plural)" },
    { id: 8, chinese: "他们", pinyin: "tāmen", english: "they, them" },
    { id: 9, chinese: "这", pinyin: "zhè", english: "this" },
    { id: 10, chinese: "那", pinyin: "nà", english: "that" },
    { id: 11, chinese: "哪", pinyin: "nǎ", english: "which, what" },
    { id: 12, chinese: "谁", pinyin: "shéi", english: "who" },
    { id: 13, chinese: "什么", pinyin: "shénme", english: "what" },
    { id: 14, chinese: "怎么", pinyin: "zěnme", english: "how, why" },
    { id: 15, chinese: "多少", pinyin: "duōshao", english: "how many, how much" },
    { id: 16, chinese: "几", pinyin: "jǐ", english: "how many, several" },
    { id: 17, chinese: "自己", pinyin: "zìjǐ", english: "oneself" },

    // Numbers
    { id: 18, chinese: "一", pinyin: "yī", english: "one" },
    { id: 19, chinese: "二", pinyin: "èr", english: "two" },
    { id: 20, chinese: "三", pinyin: "sān", english: "three" },
    { id: 21, chinese: "四", pinyin: "sì", english: "four" },
    { id: 22, chinese: "五", pinyin: "wǔ", english: "five" },
    { id: 23, chinese: "六", pinyin: "liù", english: "six" },
    { id: 24, chinese: "七", pinyin: "qī", english: "seven" },
    { id: 25, chinese: "八", pinyin: "bā", english: "eight" },
    { id: 26, chinese: "九", pinyin: "jiǔ", english: "nine" },
    { id: 27, chinese: "十", pinyin: "shí", english: "ten" },
    { id: 28, chinese: "零", pinyin: "líng", english: "zero" },
    { id: 29, chinese: "百", pinyin: "bǎi", english: "hundred" },
    { id: 30, chinese: "千", pinyin: "qiān", english: "thousand" },
    { id: 31, chinese: "万", pinyin: "wàn", english: "ten thousand" },
    { id: 32, chinese: "两", pinyin: "liǎng", english: "two (before measure word)" },
    { id: 33, chinese: "第一", pinyin: "dìyī", english: "first" },

    // Time Words
    { id: 34, chinese: "年", pinyin: "nián", english: "year" },
    { id: 35, chinese: "月", pinyin: "yuè", english: "month, moon" },
    { id: 36, chinese: "日", pinyin: "rì", english: "day, sun" },
    { id: 37, chinese: "号", pinyin: "hào", english: "date, number" },
    { id: 38, chinese: "星期", pinyin: "xīngqī", english: "week" },
    { id: 39, chinese: "今天", pinyin: "jīntiān", english: "today" },
    { id: 40, chinese: "明天", pinyin: "míngtiān", english: "tomorrow" },
    { id: 41, chinese: "昨天", pinyin: "zuótiān", english: "yesterday" },
    { id: 42, chinese: "现在", pinyin: "xiànzài", english: "now" },
    { id: 43, chinese: "时候", pinyin: "shíhou", english: "time, moment" },
    { id: 44, chinese: "点", pinyin: "diǎn", english: "o'clock, point" },
    { id: 45, chinese: "分钟", pinyin: "fēnzhōng", english: "minute" },
    { id: 46, chinese: "早上", pinyin: "zǎoshang", english: "morning" },
    { id: 47, chinese: "上午", pinyin: "shàngwǔ", english: "morning (before noon)" },
    { id: 48, chinese: "中午", pinyin: "zhōngwǔ", english: "noon" },
    { id: 49, chinese: "下午", pinyin: "xiàwǔ", english: "afternoon" },
    { id: 50, chinese: "晚上", pinyin: "wǎnshang", english: "evening, night" },
    { id: 51, chinese: "去年", pinyin: "qùnián", english: "last year" },
    { id: 52, chinese: "今年", pinyin: "jīnnián", english: "this year" },
    { id: 53, chinese: "明年", pinyin: "míngnián", english: "next year" },
    { id: 54, chinese: "以前", pinyin: "yǐqián", english: "before, ago" },
    { id: 55, chinese: "以后", pinyin: "yǐhòu", english: "after, later" },
    { id: 56, chinese: "时间", pinyin: "shíjiān", english: "time" },

    // Family
    { id: 57, chinese: "爸爸", pinyin: "bàba", english: "father, dad" },
    { id: 58, chinese: "妈妈", pinyin: "māma", english: "mother, mom" },
    { id: 59, chinese: "儿子", pinyin: "érzi", english: "son" },
    { id: 60, chinese: "女儿", pinyin: "nǚér", english: "daughter" },
    { id: 61, chinese: "哥哥", pinyin: "gēge", english: "older brother" },
    { id: 62, chinese: "姐姐", pinyin: "jiějie", english: "older sister" },
    { id: 63, chinese: "弟弟", pinyin: "dìdi", english: "younger brother" },
    { id: 64, chinese: "妹妹", pinyin: "mèimei", english: "younger sister" },
    { id: 65, chinese: "丈夫", pinyin: "zhàngfu", english: "husband" },
    { id: 66, chinese: "妻子", pinyin: "qīzi", english: "wife" },
    { id: 67, chinese: "孩子", pinyin: "háizi", english: "child, children" },
    { id: 68, chinese: "家", pinyin: "jiā", english: "home, family" },
    { id: 69, chinese: "家人", pinyin: "jiārén", english: "family members" },
    { id: 70, chinese: "朋友", pinyin: "péngyou", english: "friend" },
    { id: 71, chinese: "同学", pinyin: "tóngxué", english: "classmate" },
    { id: 72, chinese: "老师", pinyin: "lǎoshī", english: "teacher" },
    { id: 73, chinese: "学生", pinyin: "xuésheng", english: "student" },
    { id: 74, chinese: "先生", pinyin: "xiānsheng", english: "Mr., sir" },
    { id: 75, chinese: "小姐", pinyin: "xiǎojiě", english: "Miss, young lady" },
    { id: 76, chinese: "人", pinyin: "rén", english: "person, people" },
    { id: 77, chinese: "名字", pinyin: "míngzi", english: "name" },

    // Places
    { id: 78, chinese: "中国", pinyin: "Zhōngguó", english: "China" },
    { id: 79, chinese: "北京", pinyin: "Běijīng", english: "Beijing" },
    { id: 80, chinese: "上海", pinyin: "Shànghǎi", english: "Shanghai" },
    { id: 81, chinese: "学校", pinyin: "xuéxiào", english: "school" },
    { id: 82, chinese: "医院", pinyin: "yīyuàn", english: "hospital" },
    { id: 83, chinese: "商店", pinyin: "shāngdiàn", english: "store, shop" },
    { id: 84, chinese: "饭店", pinyin: "fàndiàn", english: "restaurant, hotel" },
    { id: 85, chinese: "机场", pinyin: "jīchǎng", english: "airport" },
    { id: 86, chinese: "火车站", pinyin: "huǒchēzhàn", english: "train station" },
    { id: 87, chinese: "房间", pinyin: "fángjiān", english: "room" },
    { id: 88, chinese: "教室", pinyin: "jiàoshì", english: "classroom" },
    { id: 89, chinese: "办公室", pinyin: "bàngōngshì", english: "office" },
    { id: 90, chinese: "银行", pinyin: "yínháng", english: "bank" },
    { id: 91, chinese: "超市", pinyin: "chāoshì", english: "supermarket" },
    { id: 92, chinese: "公司", pinyin: "gōngsī", english: "company" },
    { id: 93, chinese: "里", pinyin: "lǐ", english: "inside, in" },
    { id: 94, chinese: "外", pinyin: "wài", english: "outside, out" },
    { id: 95, chinese: "上", pinyin: "shàng", english: "up, above, on" },
    { id: 96, chinese: "下", pinyin: "xià", english: "down, below, under" },
    { id: 97, chinese: "前", pinyin: "qián", english: "front, before" },
    { id: 98, chinese: "后", pinyin: "hòu", english: "back, after, behind" },
    { id: 99, chinese: "左", pinyin: "zuǒ", english: "left" },
    { id: 100, chinese: "右", pinyin: "yòu", english: "right" },
    { id: 101, chinese: "旁边", pinyin: "pángbiān", english: "beside, next to" },
    { id: 102, chinese: "对面", pinyin: "duìmiàn", english: "opposite, across" },

    // Common Nouns
    { id: 103, chinese: "东西", pinyin: "dōngxi", english: "thing, stuff" },
    { id: 104, chinese: "水", pinyin: "shuǐ", english: "water" },
    { id: 105, chinese: "茶", pinyin: "chá", english: "tea" },
    { id: 106, chinese: "咖啡", pinyin: "kāfēi", english: "coffee" },
    { id: 107, chinese: "米饭", pinyin: "mǐfàn", english: "rice (cooked)" },
    { id: 108, chinese: "面条", pinyin: "miàntiáo", english: "noodles" },
    { id: 109, chinese: "菜", pinyin: "cài", english: "vegetable, dish" },
    { id: 110, chinese: "水果", pinyin: "shuǐguǒ", english: "fruit" },
    { id: 111, chinese: "苹果", pinyin: "píngguǒ", english: "apple" },
    { id: 112, chinese: "肉", pinyin: "ròu", english: "meat" },
    { id: 113, chinese: "鱼", pinyin: "yú", english: "fish" },
    { id: 114, chinese: "鸡蛋", pinyin: "jīdàn", english: "egg" },
    { id: 115, chinese: "牛奶", pinyin: "niúnǎi", english: "milk" },
    { id: 116, chinese: "面包", pinyin: "miànbāo", english: "bread" },
    { id: 117, chinese: "钱", pinyin: "qián", english: "money" },
    { id: 118, chinese: "块", pinyin: "kuài", english: "yuan (colloquial), piece" },
    { id: 119, chinese: "书", pinyin: "shū", english: "book" },
    { id: 120, chinese: "电脑", pinyin: "diànnǎo", english: "computer" },
    { id: 121, chinese: "手机", pinyin: "shǒujī", english: "mobile phone" },
    { id: 122, chinese: "电话", pinyin: "diànhuà", english: "telephone" },
    { id: 123, chinese: "电视", pinyin: "diànshì", english: "television" },
    { id: 124, chinese: "衣服", pinyin: "yīfu", english: "clothes" },
    { id: 125, chinese: "桌子", pinyin: "zhuōzi", english: "table, desk" },
    { id: 126, chinese: "椅子", pinyin: "yǐzi", english: "chair" },
    { id: 127, chinese: "门", pinyin: "mén", english: "door, gate" },
    { id: 128, chinese: "车", pinyin: "chē", english: "car, vehicle" },
    { id: 129, chinese: "飞机", pinyin: "fēijī", english: "airplane" },
    { id: 130, chinese: "火车", pinyin: "huǒchē", english: "train" },
    { id: 131, chinese: "出租车", pinyin: "chūzūchē", english: "taxi" },
    { id: 132, chinese: "路", pinyin: "lù", english: "road, way" },
    { id: 133, chinese: "天气", pinyin: "tiānqì", english: "weather" },
    { id: 134, chinese: "雨", pinyin: "yǔ", english: "rain" },
    { id: 135, chinese: "雪", pinyin: "xuě", english: "snow" },
    { id: 136, chinese: "风", pinyin: "fēng", english: "wind" },
    { id: 137, chinese: "猫", pinyin: "māo", english: "cat" },
    { id: 138, chinese: "狗", pinyin: "gǒu", english: "dog" },
    { id: 139, chinese: "药", pinyin: "yào", english: "medicine" },
    { id: 140, chinese: "票", pinyin: "piào", english: "ticket" },
    { id: 141, chinese: "事", pinyin: "shì", english: "thing, matter" },
    { id: 142, chinese: "问题", pinyin: "wèntí", english: "question, problem" },
    { id: 143, chinese: "工作", pinyin: "gōngzuò", english: "work, job" },
    { id: 144, chinese: "电影", pinyin: "diànyǐng", english: "movie, film" },
    { id: 145, chinese: "音乐", pinyin: "yīnyuè", english: "music" },
    { id: 146, chinese: "运动", pinyin: "yùndòng", english: "sports, exercise" },
    { id: 147, chinese: "报纸", pinyin: "bàozhǐ", english: "newspaper" },
    { id: 148, chinese: "字", pinyin: "zì", english: "character, word" },
    { id: 149, chinese: "汉字", pinyin: "hànzì", english: "Chinese character" },
    { id: 150, chinese: "中文", pinyin: "Zhōngwén", english: "Chinese (language)" },
    { id: 151, chinese: "英文", pinyin: "Yīngwén", english: "English (language)" },

    // Body Parts
    { id: 152, chinese: "头", pinyin: "tóu", english: "head" },
    { id: 153, chinese: "眼睛", pinyin: "yǎnjing", english: "eye" },
    { id: 154, chinese: "耳朵", pinyin: "ěrduo", english: "ear" },
    { id: 155, chinese: "鼻子", pinyin: "bízi", english: "nose" },
    { id: 156, chinese: "嘴", pinyin: "zuǐ", english: "mouth" },
    { id: 157, chinese: "手", pinyin: "shǒu", english: "hand" },
    { id: 158, chinese: "脚", pinyin: "jiǎo", english: "foot" },
    { id: 159, chinese: "身体", pinyin: "shēntǐ", english: "body" },

    // Verbs
    { id: 160, chinese: "是", pinyin: "shì", english: "to be" },
    { id: 161, chinese: "有", pinyin: "yǒu", english: "to have, there is" },
    { id: 162, chinese: "没有", pinyin: "méiyǒu", english: "don't have, there isn't" },
    { id: 163, chinese: "在", pinyin: "zài", english: "to be at, in" },
    { id: 164, chinese: "去", pinyin: "qù", english: "to go" },
    { id: 165, chinese: "来", pinyin: "lái", english: "to come" },
    { id: 166, chinese: "回", pinyin: "huí", english: "to return" },
    { id: 167, chinese: "到", pinyin: "dào", english: "to arrive, to" },
    { id: 168, chinese: "走", pinyin: "zǒu", english: "to walk, to go" },
    { id: 169, chinese: "跑", pinyin: "pǎo", english: "to run" },
    { id: 170, chinese: "坐", pinyin: "zuò", english: "to sit" },
    { id: 171, chinese: "站", pinyin: "zhàn", english: "to stand" },
    { id: 172, chinese: "睡觉", pinyin: "shuìjiào", english: "to sleep" },
    { id: 173, chinese: "起床", pinyin: "qǐchuáng", english: "to get up" },
    { id: 174, chinese: "吃", pinyin: "chī", english: "to eat" },
    { id: 175, chinese: "喝", pinyin: "hē", english: "to drink" },
    { id: 176, chinese: "看", pinyin: "kàn", english: "to look, to watch" },
    { id: 177, chinese: "听", pinyin: "tīng", english: "to listen" },
    { id: 178, chinese: "说", pinyin: "shuō", english: "to speak, to say" },
    { id: 179, chinese: "读", pinyin: "dú", english: "to read" },
    { id: 180, chinese: "写", pinyin: "xiě", english: "to write" },
    { id: 181, chinese: "学习", pinyin: "xuéxí", english: "to study, to learn" },
    { id: 182, chinese: "教", pinyin: "jiāo", english: "to teach" },
    { id: 183, chinese: "做", pinyin: "zuò", english: "to do, to make" },
    { id: 184, chinese: "买", pinyin: "mǎi", english: "to buy" },
    { id: 185, chinese: "卖", pinyin: "mài", english: "to sell" },
    { id: 186, chinese: "给", pinyin: "gěi", english: "to give" },
    { id: 187, chinese: "送", pinyin: "sòng", english: "to send, to give (gift)" },
    { id: 188, chinese: "找", pinyin: "zhǎo", english: "to look for" },
    { id: 189, chinese: "用", pinyin: "yòng", english: "to use" },
    { id: 190, chinese: "穿", pinyin: "chuān", english: "to wear" },
    { id: 191, chinese: "想", pinyin: "xiǎng", english: "to think, to want" },
    { id: 192, chinese: "知道", pinyin: "zhīdào", english: "to know" },
    { id: 193, chinese: "认识", pinyin: "rènshi", english: "to know (person)" },
    { id: 194, chinese: "懂", pinyin: "dǒng", english: "to understand" },
    { id: 195, chinese: "会", pinyin: "huì", english: "can, will" },
    { id: 196, chinese: "能", pinyin: "néng", english: "can, be able to" },
    { id: 197, chinese: "可以", pinyin: "kěyǐ", english: "can, may" },
    { id: 198, chinese: "要", pinyin: "yào", english: "to want, will" },
    { id: 199, chinese: "应该", pinyin: "yīnggāi", english: "should" },
    { id: 200, chinese: "喜欢", pinyin: "xǐhuan", english: "to like" },
    { id: 201, chinese: "爱", pinyin: "ài", english: "to love" },
    { id: 202, chinese: "觉得", pinyin: "juéde", english: "to feel, to think" },
    { id: 203, chinese: "希望", pinyin: "xīwàng", english: "to hope" },
    { id: 204, chinese: "帮助", pinyin: "bāngzhù", english: "to help" },
    { id: 205, chinese: "等", pinyin: "děng", english: "to wait" },
    { id: 206, chinese: "问", pinyin: "wèn", english: "to ask" },
    { id: 207, chinese: "回答", pinyin: "huídá", english: "to answer" },
    { id: 208, chinese: "告诉", pinyin: "gàosu", english: "to tell" },
    { id: 209, chinese: "叫", pinyin: "jiào", english: "to call, to be called" },
    { id: 210, chinese: "打电话", pinyin: "dǎ diànhuà", english: "to make a phone call" },
    { id: 211, chinese: "开", pinyin: "kāi", english: "to open, to turn on" },
    { id: 212, chinese: "关", pinyin: "guān", english: "to close, to turn off" },
    { id: 213, chinese: "进", pinyin: "jìn", english: "to enter" },
    { id: 214, chinese: "出", pinyin: "chū", english: "to exit, to go out" },
    { id: 215, chinese: "上", pinyin: "shàng", english: "to go up, to attend" },
    { id: 216, chinese: "下", pinyin: "xià", english: "to go down" },
    { id: 217, chinese: "玩", pinyin: "wán", english: "to play" },
    { id: 218, chinese: "唱歌", pinyin: "chànggē", english: "to sing" },
    { id: 219, chinese: "跳舞", pinyin: "tiàowǔ", english: "to dance" },
    { id: 220, chinese: "游泳", pinyin: "yóuyǒng", english: "to swim" },
    { id: 221, chinese: "踢足球", pinyin: "tī zúqiú", english: "to play soccer" },
    { id: 222, chinese: "打篮球", pinyin: "dǎ lánqiú", english: "to play basketball" },
    { id: 223, chinese: "开始", pinyin: "kāishǐ", english: "to begin, to start" },
    { id: 224, chinese: "完成", pinyin: "wánchéng", english: "to complete, to finish" },
    { id: 225, chinese: "休息", pinyin: "xiūxi", english: "to rest" },
    { id: 226, chinese: "准备", pinyin: "zhǔnbèi", english: "to prepare" },
    { id: 227, chinese: "介绍", pinyin: "jièshào", english: "to introduce" },
    { id: 228, chinese: "生病", pinyin: "shēngbìng", english: "to get sick" },
    { id: 229, chinese: "笑", pinyin: "xiào", english: "to laugh, to smile" },
    { id: 230, chinese: "哭", pinyin: "kū", english: "to cry" },
    { id: 231, chinese: "住", pinyin: "zhù", english: "to live, to stay" },
    { id: 232, chinese: "洗", pinyin: "xǐ", english: "to wash" },
    { id: 233, chinese: "见面", pinyin: "jiànmiàn", english: "to meet" },
    { id: 234, chinese: "旅游", pinyin: "lǚyóu", english: "to travel" },
    { id: 235, chinese: "上班", pinyin: "shàngbān", english: "to go to work" },
    { id: 236, chinese: "下班", pinyin: "xiàbān", english: "to get off work" },

    // Adjectives
    { id: 237, chinese: "好", pinyin: "hǎo", english: "good" },
    { id: 238, chinese: "坏", pinyin: "huài", english: "bad" },
    { id: 239, chinese: "大", pinyin: "dà", english: "big, large" },
    { id: 240, chinese: "小", pinyin: "xiǎo", english: "small, little" },
    { id: 241, chinese: "多", pinyin: "duō", english: "many, much" },
    { id: 242, chinese: "少", pinyin: "shǎo", english: "few, little" },
    { id: 243, chinese: "高", pinyin: "gāo", english: "tall, high" },
    { id: 244, chinese: "矮", pinyin: "ǎi", english: "short (height)" },
    { id: 245, chinese: "长", pinyin: "cháng", english: "long" },
    { id: 246, chinese: "短", pinyin: "duǎn", english: "short (length)" },
    { id: 247, chinese: "新", pinyin: "xīn", english: "new" },
    { id: 248, chinese: "旧", pinyin: "jiù", english: "old (things)" },
    { id: 249, chinese: "老", pinyin: "lǎo", english: "old (age)" },
    { id: 250, chinese: "年轻", pinyin: "niánqīng", english: "young" },
    { id: 251, chinese: "快", pinyin: "kuài", english: "fast, quick" },
    { id: 252, chinese: "慢", pinyin: "màn", english: "slow" },
    { id: 253, chinese: "早", pinyin: "zǎo", english: "early" },
    { id: 254, chinese: "晚", pinyin: "wǎn", english: "late" },
    { id: 255, chinese: "热", pinyin: "rè", english: "hot" },
    { id: 256, chinese: "冷", pinyin: "lěng", english: "cold" },
    { id: 257, chinese: "暖和", pinyin: "nuǎnhuo", english: "warm" },
    { id: 258, chinese: "凉快", pinyin: "liángkuai", english: "cool" },
    { id: 259, chinese: "漂亮", pinyin: "piàoliang", english: "beautiful, pretty" },
    { id: 260, chinese: "帅", pinyin: "shuài", english: "handsome" },
    { id: 261, chinese: "难看", pinyin: "nánkàn", english: "ugly" },
    { id: 262, chinese: "高兴", pinyin: "gāoxìng", english: "happy" },
    { id: 263, chinese: "快乐", pinyin: "kuàilè", english: "happy, joyful" },
    { id: 264, chinese: "难过", pinyin: "nánguò", english: "sad" },
    { id: 265, chinese: "累", pinyin: "lèi", english: "tired" },
    { id: 266, chinese: "饿", pinyin: "è", english: "hungry" },
    { id: 267, chinese: "渴", pinyin: "kě", english: "thirsty" },
    { id: 268, chinese: "忙", pinyin: "máng", english: "busy" },
    { id: 269, chinese: "贵", pinyin: "guì", english: "expensive" },
    { id: 270, chinese: "便宜", pinyin: "piányi", english: "cheap" },
    { id: 271, chinese: "容易", pinyin: "róngyì", english: "easy" },
    { id: 272, chinese: "难", pinyin: "nán", english: "difficult" },
    { id: 273, chinese: "对", pinyin: "duì", english: "correct, right" },
    { id: 274, chinese: "错", pinyin: "cuò", english: "wrong" },
    { id: 275, chinese: "近", pinyin: "jìn", english: "near" },
    { id: 276, chinese: "远", pinyin: "yuǎn", english: "far" },
    { id: 277, chinese: "重要", pinyin: "zhòngyào", english: "important" },
    { id: 278, chinese: "有意思", pinyin: "yǒu yìsi", english: "interesting" },
    { id: 279, chinese: "干净", pinyin: "gānjìng", english: "clean" },
    { id: 280, chinese: "安静", pinyin: "ānjìng", english: "quiet" },
    { id: 281, chinese: "聪明", pinyin: "cōngming", english: "smart, clever" },
    { id: 282, chinese: "健康", pinyin: "jiànkāng", english: "healthy" },
    { id: 283, chinese: "舒服", pinyin: "shūfu", english: "comfortable" },
    { id: 284, chinese: "红", pinyin: "hóng", english: "red" },
    { id: 285, chinese: "黄", pinyin: "huáng", english: "yellow" },
    { id: 286, chinese: "蓝", pinyin: "lán", english: "blue" },
    { id: 287, chinese: "绿", pinyin: "lǜ", english: "green" },
    { id: 288, chinese: "白", pinyin: "bái", english: "white" },
    { id: 289, chinese: "黑", pinyin: "hēi", english: "black" },

    // Adverbs
    { id: 290, chinese: "很", pinyin: "hěn", english: "very" },
    { id: 291, chinese: "太", pinyin: "tài", english: "too (much)" },
    { id: 292, chinese: "非常", pinyin: "fēicháng", english: "very, extremely" },
    { id: 293, chinese: "真", pinyin: "zhēn", english: "really, truly" },
    { id: 294, chinese: "最", pinyin: "zuì", english: "most" },
    { id: 295, chinese: "更", pinyin: "gèng", english: "more, even more" },
    { id: 296, chinese: "比较", pinyin: "bǐjiào", english: "relatively, quite" },
    { id: 297, chinese: "也", pinyin: "yě", english: "also, too" },
    { id: 298, chinese: "都", pinyin: "dōu", english: "all, both" },
    { id: 299, chinese: "还", pinyin: "hái", english: "still, also" },
    { id: 300, chinese: "再", pinyin: "zài", english: "again" },
    { id: 301, chinese: "又", pinyin: "yòu", english: "again, also" },
    { id: 302, chinese: "就", pinyin: "jiù", english: "then, just" },
    { id: 303, chinese: "才", pinyin: "cái", english: "only then, just" },
    { id: 304, chinese: "不", pinyin: "bù", english: "not" },
    { id: 305, chinese: "没", pinyin: "méi", english: "not, have not" },
    { id: 306, chinese: "别", pinyin: "bié", english: "don't" },
    { id: 307, chinese: "已经", pinyin: "yǐjīng", english: "already" },
    { id: 308, chinese: "正在", pinyin: "zhèngzài", english: "in the process of" },
    { id: 309, chinese: "一起", pinyin: "yìqǐ", english: "together" },
    { id: 310, chinese: "一直", pinyin: "yìzhí", english: "always, continuously" },
    { id: 311, chinese: "常常", pinyin: "chángcháng", english: "often" },
    { id: 312, chinese: "有时候", pinyin: "yǒushíhou", english: "sometimes" },
    { id: 313, chinese: "从来", pinyin: "cónglái", english: "never (before)" },
    { id: 314, chinese: "一定", pinyin: "yídìng", english: "certainly, definitely" },
    { id: 315, chinese: "可能", pinyin: "kěnéng", english: "maybe, possibly" },
    { id: 316, chinese: "大概", pinyin: "dàgài", english: "probably, about" },
    { id: 317, chinese: "马上", pinyin: "mǎshàng", english: "immediately" },
    { id: 318, chinese: "刚才", pinyin: "gāngcái", english: "just now" },

    // Prepositions & Conjunctions
    { id: 319, chinese: "和", pinyin: "hé", english: "and, with" },
    { id: 320, chinese: "跟", pinyin: "gēn", english: "with, and" },
    { id: 321, chinese: "从", pinyin: "cóng", english: "from" },
    { id: 322, chinese: "往", pinyin: "wǎng", english: "towards" },
    { id: 323, chinese: "向", pinyin: "xiàng", english: "towards" },
    { id: 324, chinese: "离", pinyin: "lí", english: "from (distance)" },
    { id: 325, chinese: "对", pinyin: "duì", english: "to, towards" },
    { id: 326, chinese: "比", pinyin: "bǐ", english: "compared to" },
    { id: 327, chinese: "因为", pinyin: "yīnwèi", english: "because" },
    { id: 328, chinese: "所以", pinyin: "suǒyǐ", english: "so, therefore" },
    { id: 329, chinese: "如果", pinyin: "rúguǒ", english: "if" },
    { id: 330, chinese: "虽然", pinyin: "suīrán", english: "although" },
    { id: 331, chinese: "但是", pinyin: "dànshì", english: "but, however" },
    { id: 332, chinese: "或者", pinyin: "huòzhě", english: "or" },
    { id: 333, chinese: "还是", pinyin: "háishi", english: "or (in questions)" },

    // Measure Words
    { id: 334, chinese: "个", pinyin: "gè", english: "general measure word" },
    { id: 335, chinese: "本", pinyin: "běn", english: "MW for books" },
    { id: 336, chinese: "张", pinyin: "zhāng", english: "MW for flat objects" },
    { id: 337, chinese: "件", pinyin: "jiàn", english: "MW for clothes, matters" },
    { id: 338, chinese: "条", pinyin: "tiáo", english: "MW for long things" },
    { id: 339, chinese: "只", pinyin: "zhī", english: "MW for animals" },
    { id: 340, chinese: "杯", pinyin: "bēi", english: "MW for cups" },
    { id: 341, chinese: "瓶", pinyin: "píng", english: "MW for bottles" },
    { id: 342, chinese: "碗", pinyin: "wǎn", english: "MW for bowls" },
    { id: 343, chinese: "次", pinyin: "cì", english: "MW for times" },
    { id: 344, chinese: "岁", pinyin: "suì", english: "years old" },
    { id: 345, chinese: "层", pinyin: "céng", english: "MW for floors" },
    { id: 346, chinese: "些", pinyin: "xiē", english: "some, a few" },

    // Common Phrases & Expressions
    { id: 347, chinese: "你好", pinyin: "nǐ hǎo", english: "hello" },
    { id: 348, chinese: "谢谢", pinyin: "xièxie", english: "thank you" },
    { id: 349, chinese: "不客气", pinyin: "bú kèqi", english: "you're welcome" },
    { id: 350, chinese: "对不起", pinyin: "duìbuqǐ", english: "sorry" },
    { id: 351, chinese: "没关系", pinyin: "méi guānxi", english: "it doesn't matter" },
    { id: 352, chinese: "再见", pinyin: "zàijiàn", english: "goodbye" },
    { id: 353, chinese: "请", pinyin: "qǐng", english: "please" },
    { id: 354, chinese: "欢迎", pinyin: "huānyíng", english: "welcome" },
    { id: 355, chinese: "生日快乐", pinyin: "shēngrì kuàilè", english: "happy birthday" },
    { id: 356, chinese: "新年快乐", pinyin: "xīnnián kuàilè", english: "happy new year" },
    { id: 357, chinese: "恭喜", pinyin: "gōngxǐ", english: "congratulations" },
    { id: 358, chinese: "加油", pinyin: "jiāyóu", english: "come on, go for it" },

    // More Common Words
    { id: 359, chinese: "每", pinyin: "měi", english: "every, each" },
    { id: 360, chinese: "全", pinyin: "quán", english: "whole, entire" },
    { id: 361, chinese: "只", pinyin: "zhǐ", english: "only" },
    { id: 362, chinese: "其他", pinyin: "qítā", english: "other" },
    { id: 363, chinese: "别的", pinyin: "biéde", english: "other, else" },
    { id: 364, chinese: "为了", pinyin: "wèile", english: "in order to" },
    { id: 365, chinese: "关于", pinyin: "guānyú", english: "about, regarding" },
    { id: 366, chinese: "除了", pinyin: "chúle", english: "except, besides" },
    { id: 367, chinese: "根据", pinyin: "gēnjù", english: "according to" },
    { id: 368, chinese: "通过", pinyin: "tōngguò", english: "through, via" },
    { id: 369, chinese: "得", pinyin: "de/děi", english: "particle/must" },
    { id: 370, chinese: "地", pinyin: "de", english: "adverb particle" },
    { id: 371, chinese: "的", pinyin: "de", english: "possessive particle" },
    { id: 372, chinese: "了", pinyin: "le", english: "completion particle" },
    { id: 373, chinese: "过", pinyin: "guò", english: "experience particle" },
    { id: 374, chinese: "着", pinyin: "zhe", english: "continuous particle" },
    { id: 375, chinese: "吗", pinyin: "ma", english: "question particle" },
    { id: 376, chinese: "呢", pinyin: "ne", english: "modal particle" },
    { id: 377, chinese: "吧", pinyin: "ba", english: "suggestion particle" },
    { id: 378, chinese: "啊", pinyin: "a", english: "exclamation particle" },

    // Additional Important Words
    { id: 379, chinese: "地方", pinyin: "dìfang", english: "place" },
    { id: 380, chinese: "国家", pinyin: "guójiā", english: "country" },
    { id: 381, chinese: "世界", pinyin: "shìjiè", english: "world" },
    { id: 382, chinese: "城市", pinyin: "chéngshì", english: "city" },
    { id: 383, chinese: "环境", pinyin: "huánjìng", english: "environment" },
    { id: 384, chinese: "情况", pinyin: "qíngkuàng", english: "situation" },
    { id: 385, chinese: "方法", pinyin: "fāngfǎ", english: "method" },
    { id: 386, chinese: "结果", pinyin: "jiéguǒ", english: "result" },
    { id: 387, chinese: "原因", pinyin: "yuányīn", english: "reason, cause" },
    { id: 388, chinese: "目的", pinyin: "mùdì", english: "purpose" },
    { id: 389, chinese: "历史", pinyin: "lìshǐ", english: "history" },
    { id: 390, chinese: "文化", pinyin: "wénhuà", english: "culture" },
    { id: 391, chinese: "经济", pinyin: "jīngjì", english: "economy" },
    { id: 392, chinese: "社会", pinyin: "shèhuì", english: "society" },
    { id: 393, chinese: "科学", pinyin: "kēxué", english: "science" },
    { id: 394, chinese: "技术", pinyin: "jìshù", english: "technology" },
    { id: 395, chinese: "艺术", pinyin: "yìshù", english: "art" },
    { id: 396, chinese: "教育", pinyin: "jiàoyù", english: "education" },
    { id: 397, chinese: "网络", pinyin: "wǎngluò", english: "internet, network" },
    { id: 398, chinese: "信息", pinyin: "xìnxī", english: "information" },
    { id: 399, chinese: "数字", pinyin: "shùzì", english: "number, digit" },
    { id: 400, chinese: "照片", pinyin: "zhàopiàn", english: "photo" },
    { id: 401, chinese: "节目", pinyin: "jiémù", english: "program, show" },
    { id: 402, chinese: "比赛", pinyin: "bǐsài", english: "competition, match" },
    { id: 403, chinese: "活动", pinyin: "huódòng", english: "activity" },
    { id: 404, chinese: "会议", pinyin: "huìyì", english: "meeting" },
    { id: 405, chinese: "计划", pinyin: "jìhuà", english: "plan" },
    { id: 406, chinese: "决定", pinyin: "juédìng", english: "decision, to decide" },
    { id: 407, chinese: "选择", pinyin: "xuǎnzé", english: "choice, to choose" },
    { id: 408, chinese: "同意", pinyin: "tóngyì", english: "to agree" },
    { id: 409, chinese: "反对", pinyin: "fǎnduì", english: "to oppose" },
    { id: 410, chinese: "支持", pinyin: "zhīchí", english: "to support" },
    { id: 411, chinese: "相信", pinyin: "xiāngxìn", english: "to believe" },
    { id: 412, chinese: "发现", pinyin: "fāxiàn", english: "to discover" },
    { id: 413, chinese: "了解", pinyin: "liǎojiě", english: "to understand" },
    { id: 414, chinese: "解决", pinyin: "jiějué", english: "to solve" },
    { id: 415, chinese: "参加", pinyin: "cānjiā", english: "to participate" },
    { id: 416, chinese: "表示", pinyin: "biǎoshì", english: "to express" },
    { id: 417, chinese: "提供", pinyin: "tígōng", english: "to provide" },
    { id: 418, chinese: "保护", pinyin: "bǎohù", english: "to protect" },
    { id: 419, chinese: "发展", pinyin: "fāzhǎn", english: "to develop" },
    { id: 420, chinese: "改变", pinyin: "gǎibiàn", english: "to change" },
    { id: 421, chinese: "增加", pinyin: "zēngjiā", english: "to increase" },
    { id: 422, chinese: "减少", pinyin: "jiǎnshǎo", english: "to decrease" },
    { id: 423, chinese: "提高", pinyin: "tígāo", english: "to improve" },
    { id: 424, chinese: "降低", pinyin: "jiàngdī", english: "to lower" },
    { id: 425, chinese: "影响", pinyin: "yǐngxiǎng", english: "influence, to affect" },
    { id: 426, chinese: "注意", pinyin: "zhùyì", english: "to pay attention" },
    { id: 427, chinese: "记得", pinyin: "jìde", english: "to remember" },
    { id: 428, chinese: "忘记", pinyin: "wàngjì", english: "to forget" },
    { id: 429, chinese: "检查", pinyin: "jiǎnchá", english: "to check" },
    { id: 430, chinese: "练习", pinyin: "liànxí", english: "to practice" },
    { id: 431, chinese: "复习", pinyin: "fùxí", english: "to review" },
    { id: 432, chinese: "考试", pinyin: "kǎoshì", english: "exam, to take exam" },
    { id: 433, chinese: "毕业", pinyin: "bìyè", english: "to graduate" },
    { id: 434, chinese: "成功", pinyin: "chénggōng", english: "success, to succeed" },
    { id: 435, chinese: "失败", pinyin: "shībài", english: "failure, to fail" },
    { id: 436, chinese: "努力", pinyin: "nǔlì", english: "to work hard" },
    { id: 437, chinese: "坚持", pinyin: "jiānchí", english: "to persist" },
    { id: 438, chinese: "放弃", pinyin: "fàngqì", english: "to give up" },
    { id: 439, chinese: "接受", pinyin: "jiēshòu", english: "to accept" },
    { id: 440, chinese: "拒绝", pinyin: "jùjué", english: "to refuse" },
    { id: 441, chinese: "满意", pinyin: "mǎnyì", english: "satisfied" },
    { id: 442, chinese: "失望", pinyin: "shīwàng", english: "disappointed" },
    { id: 443, chinese: "担心", pinyin: "dānxīn", english: "worried" },
    { id: 444, chinese: "紧张", pinyin: "jǐnzhāng", english: "nervous" },
    { id: 445, chinese: "害怕", pinyin: "hàipà", english: "afraid" },
    { id: 446, chinese: "生气", pinyin: "shēngqì", english: "angry" },
    { id: 447, chinese: "着急", pinyin: "zháojí", english: "anxious" },
    { id: 448, chinese: "奇怪", pinyin: "qíguài", english: "strange" },
    { id: 449, chinese: "特别", pinyin: "tèbié", english: "special, especially" },
    { id: 450, chinese: "普通", pinyin: "pǔtōng", english: "ordinary, common" },
    { id: 451, chinese: "一般", pinyin: "yìbān", english: "general, usually" },
    { id: 452, chinese: "正常", pinyin: "zhèngcháng", english: "normal" },
    { id: 453, chinese: "简单", pinyin: "jiǎndān", english: "simple" },
    { id: 454, chinese: "复杂", pinyin: "fùzá", english: "complicated" },
    { id: 455, chinese: "清楚", pinyin: "qīngchu", english: "clear" },
    { id: 456, chinese: "认真", pinyin: "rènzhēn", english: "serious, careful" },
    { id: 457, chinese: "仔细", pinyin: "zǐxì", english: "careful, detailed" },
    { id: 458, chinese: "方便", pinyin: "fāngbiàn", english: "convenient" },
    { id: 459, chinese: "必须", pinyin: "bìxū", english: "must" },
    { id: 460, chinese: "需要", pinyin: "xūyào", english: "need" },
    { id: 461, chinese: "愿意", pinyin: "yuànyì", english: "willing" },
    { id: 462, chinese: "敢", pinyin: "gǎn", english: "dare" },
    { id: 463, chinese: "打算", pinyin: "dǎsuàn", english: "to plan" },
    { id: 464, chinese: "经常", pinyin: "jīngcháng", english: "often" },
    { id: 465, chinese: "偶尔", pinyin: "ǒuěr", english: "occasionally" },
    { id: 466, chinese: "总是", pinyin: "zǒngshì", english: "always" },
    { id: 467, chinese: "终于", pinyin: "zhōngyú", english: "finally" },
    { id: 468, chinese: "突然", pinyin: "tūrán", english: "suddenly" },
    { id: 469, chinese: "首先", pinyin: "shǒuxiān", english: "first of all" },
    { id: 470, chinese: "然后", pinyin: "ránhòu", english: "then, after that" },
    { id: 471, chinese: "最后", pinyin: "zuìhòu", english: "finally, at last" },
    { id: 472, chinese: "只要", pinyin: "zhǐyào", english: "as long as" },
    { id: 473, chinese: "即使", pinyin: "jíshǐ", english: "even if" },
    { id: 474, chinese: "不管", pinyin: "bùguǎn", english: "no matter" },
    { id: 475, chinese: "而且", pinyin: "érqiě", english: "moreover" },
    { id: 476, chinese: "不但", pinyin: "búdàn", english: "not only" },
    { id: 477, chinese: "而是", pinyin: "érshì", english: "but rather" },
    { id: 478, chinese: "无论", pinyin: "wúlùn", english: "regardless" },
    { id: 479, chinese: "否则", pinyin: "fǒuzé", english: "otherwise" },
    { id: 480, chinese: "作为", pinyin: "zuòwéi", english: "as, being" },
    { id: 481, chinese: "关系", pinyin: "guānxi", english: "relationship" },
    { id: 482, chinese: "机会", pinyin: "jīhuì", english: "opportunity" },
    { id: 483, chinese: "经验", pinyin: "jīngyàn", english: "experience" },
    { id: 484, chinese: "能力", pinyin: "nénglì", english: "ability" },
    { id: 485, chinese: "水平", pinyin: "shuǐpíng", english: "level" },
    { id: 486, chinese: "态度", pinyin: "tàidu", english: "attitude" },
    { id: 487, chinese: "意见", pinyin: "yìjiàn", english: "opinion" },
    { id: 488, chinese: "建议", pinyin: "jiànyì", english: "suggestion" },
    { id: 489, chinese: "办法", pinyin: "bànfǎ", english: "way, method" },
    { id: 490, chinese: "作用", pinyin: "zuòyòng", english: "function, effect" },
    { id: 491, chinese: "效果", pinyin: "xiàoguǒ", english: "effect, result" },
    { id: 492, chinese: "标准", pinyin: "biāozhǔn", english: "standard" },
    { id: 493, chinese: "条件", pinyin: "tiáojiàn", english: "condition" },
    { id: 494, chinese: "基础", pinyin: "jīchǔ", english: "foundation" },
    { id: 495, chinese: "内容", pinyin: "nèiróng", english: "content" },
    { id: 496, chinese: "形式", pinyin: "xíngshì", english: "form" },
    { id: 497, chinese: "过程", pinyin: "guòchéng", english: "process" },
    { id: 498, chinese: "范围", pinyin: "fànwéi", english: "scope, range" },
    { id: 499, chinese: "程度", pinyin: "chéngdù", english: "degree, extent" },
    { id: 500, chinese: "数量", pinyin: "shùliàng", english: "quantity" }
];

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = HSK_VOCABULARY;
}
