// HSK 3.0 Level 1 Vocabulary Database
// Contains approximately 500 words required for HSK 3.0 Level 1

const HSK_VOCABULARY = [
    // Pronouns
    { id: 1, chinese: "我", pinyin: "wǒ", english: "I, me", example: { chinese: "我是学生。", pinyin: "Wǒ shì xuésheng.", english: "I am a student." } },
    { id: 2, chinese: "你", pinyin: "nǐ", english: "you", example: { chinese: "你好吗？", pinyin: "Nǐ hǎo ma?", english: "How are you?" } },
    { id: 3, chinese: "他", pinyin: "tā", english: "he, him", example: { chinese: "他是我的朋友。", pinyin: "Tā shì wǒ de péngyou.", english: "He is my friend." } },
    { id: 4, chinese: "她", pinyin: "tā", english: "she, her", example: { chinese: "她很漂亮。", pinyin: "Tā hěn piàoliang.", english: "She is very beautiful." } },
    { id: 5, chinese: "它", pinyin: "tā", english: "it", example: { chinese: "它是一只猫。", pinyin: "Tā shì yì zhī māo.", english: "It is a cat." } },
    { id: 6, chinese: "我们", pinyin: "wǒmen", english: "we, us", example: { chinese: "我们一起去吧。", pinyin: "Wǒmen yìqǐ qù ba.", english: "Let's go together." } },
    { id: 7, chinese: "你们", pinyin: "nǐmen", english: "you (plural)", example: { chinese: "你们是哪国人？", pinyin: "Nǐmen shì nǎ guó rén?", english: "What country are you from?" } },
    { id: 8, chinese: "他们", pinyin: "tāmen", english: "they, them", example: { chinese: "他们在公园里。", pinyin: "Tāmen zài gōngyuán lǐ.", english: "They are in the park." } },
    { id: 9, chinese: "这", pinyin: "zhè", english: "this", example: { chinese: "这是什么？", pinyin: "Zhè shì shénme?", english: "What is this?" } },
    { id: 10, chinese: "那", pinyin: "nà", english: "that", example: { chinese: "那是我的书。", pinyin: "Nà shì wǒ de shū.", english: "That is my book." } },
    { id: 11, chinese: "哪", pinyin: "nǎ", english: "which, what", example: { chinese: "你住在哪儿？", pinyin: "Nǐ zhù zài nǎr?", english: "Where do you live?" } },
    { id: 12, chinese: "谁", pinyin: "shéi", english: "who", example: { chinese: "他是谁？", pinyin: "Tā shì shéi?", english: "Who is he?" } },
    { id: 13, chinese: "什么", pinyin: "shénme", english: "what", example: { chinese: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", english: "What is your name?" } },
    { id: 14, chinese: "怎么", pinyin: "zěnme", english: "how, why", example: { chinese: "这个字怎么读？", pinyin: "Zhège zì zěnme dú?", english: "How do you read this character?" } },
    { id: 15, chinese: "多少", pinyin: "duōshao", english: "how many, how much", example: { chinese: "这个多少钱？", pinyin: "Zhège duōshao qián?", english: "How much is this?" } },
    { id: 16, chinese: "几", pinyin: "jǐ", english: "how many, several", example: { chinese: "你有几个孩子？", pinyin: "Nǐ yǒu jǐ ge háizi?", english: "How many children do you have?" } },
    { id: 17, chinese: "自己", pinyin: "zìjǐ", english: "oneself", example: { chinese: "我自己做饭。", pinyin: "Wǒ zìjǐ zuòfàn.", english: "I cook by myself." } },

    // Numbers
    { id: 18, chinese: "一", pinyin: "yī", english: "one", example: { chinese: "我要一杯水。", pinyin: "Wǒ yào yì bēi shuǐ.", english: "I want a glass of water." } },
    { id: 19, chinese: "二", pinyin: "èr", english: "two", example: { chinese: "现在两点二十。", pinyin: "Xiànzài liǎng diǎn èrshí.", english: "It's 2:20 now." } },
    { id: 20, chinese: "三", pinyin: "sān", english: "three", example: { chinese: "我有三个姐姐。", pinyin: "Wǒ yǒu sān ge jiějie.", english: "I have three older sisters." } },
    { id: 21, chinese: "四", pinyin: "sì", english: "four", example: { chinese: "一年有四个季节。", pinyin: "Yì nián yǒu sì ge jìjié.", english: "A year has four seasons." } },
    { id: 22, chinese: "五", pinyin: "wǔ", english: "five", example: { chinese: "我每天工作五个小时。", pinyin: "Wǒ měitiān gōngzuò wǔ ge xiǎoshí.", english: "I work five hours every day." } },
    { id: 23, chinese: "六", pinyin: "liù", english: "six", example: { chinese: "他六岁了。", pinyin: "Tā liù suì le.", english: "He is six years old." } },
    { id: 24, chinese: "七", pinyin: "qī", english: "seven", example: { chinese: "一个星期有七天。", pinyin: "Yí ge xīngqī yǒu qī tiān.", english: "A week has seven days." } },
    { id: 25, chinese: "八", pinyin: "bā", english: "eight", example: { chinese: "我早上八点上班。", pinyin: "Wǒ zǎoshang bā diǎn shàngbān.", english: "I go to work at 8 in the morning." } },
    { id: 26, chinese: "九", pinyin: "jiǔ", english: "nine", example: { chinese: "九月是秋天。", pinyin: "Jiǔ yuè shì qiūtiān.", english: "September is autumn." } },
    { id: 27, chinese: "十", pinyin: "shí", english: "ten", example: { chinese: "这本书十块钱。", pinyin: "Zhè běn shū shí kuài qián.", english: "This book costs ten yuan." } },
    { id: 28, chinese: "零", pinyin: "líng", english: "zero", example: { chinese: "今天零下五度。", pinyin: "Jīntiān líng xià wǔ dù.", english: "It's minus five degrees today." } },
    { id: 29, chinese: "百", pinyin: "bǎi", english: "hundred", example: { chinese: "这件衣服三百块。", pinyin: "Zhè jiàn yīfu sānbǎi kuài.", english: "This piece of clothing costs 300 yuan." } },
    { id: 30, chinese: "千", pinyin: "qiān", english: "thousand", example: { chinese: "这个手机两千块。", pinyin: "Zhège shǒujī liǎngqiān kuài.", english: "This phone costs 2000 yuan." } },
    { id: 31, chinese: "万", pinyin: "wàn", english: "ten thousand", example: { chinese: "北京有两千万人。", pinyin: "Běijīng yǒu liǎngqiān wàn rén.", english: "Beijing has 20 million people." } },
    { id: 32, chinese: "两", pinyin: "liǎng", english: "two (before measure word)", example: { chinese: "我有两个弟弟。", pinyin: "Wǒ yǒu liǎng ge dìdi.", english: "I have two younger brothers." } },
    { id: 33, chinese: "第一", pinyin: "dìyī", english: "first", example: { chinese: "他是第一名。", pinyin: "Tā shì dìyī míng.", english: "He is first place." } },

    // Time Words
    { id: 34, chinese: "年", pinyin: "nián", english: "year", example: { chinese: "新年快乐！", pinyin: "Xīnnián kuàilè!", english: "Happy New Year!" } },
    { id: 35, chinese: "月", pinyin: "yuè", english: "month, moon", example: { chinese: "今天的月亮很美。", pinyin: "Jīntiān de yuèliang hěn měi.", english: "The moon is beautiful today." } },
    { id: 36, chinese: "日", pinyin: "rì", english: "day, sun", example: { chinese: "今天是五月一日。", pinyin: "Jīntiān shì wǔ yuè yī rì.", english: "Today is May 1st." } },
    { id: 37, chinese: "号", pinyin: "hào", english: "date, number", example: { chinese: "今天几号？", pinyin: "Jīntiān jǐ hào?", english: "What's the date today?" } },
    { id: 38, chinese: "星期", pinyin: "xīngqī", english: "week", example: { chinese: "今天星期几？", pinyin: "Jīntiān xīngqī jǐ?", english: "What day is it today?" } },
    { id: 39, chinese: "今天", pinyin: "jīntiān", english: "today", example: { chinese: "今天天气很好。", pinyin: "Jīntiān tiānqì hěn hǎo.", english: "The weather is nice today." } },
    { id: 40, chinese: "明天", pinyin: "míngtiān", english: "tomorrow", example: { chinese: "明天我们去看电影。", pinyin: "Míngtiān wǒmen qù kàn diànyǐng.", english: "We'll go watch a movie tomorrow." } },
    { id: 41, chinese: "昨天", pinyin: "zuótiān", english: "yesterday", example: { chinese: "昨天我很忙。", pinyin: "Zuótiān wǒ hěn máng.", english: "I was very busy yesterday." } },
    { id: 42, chinese: "现在", pinyin: "xiànzài", english: "now", example: { chinese: "现在几点了？", pinyin: "Xiànzài jǐ diǎn le?", english: "What time is it now?" } },
    { id: 43, chinese: "时候", pinyin: "shíhou", english: "time, moment", example: { chinese: "你什么时候来？", pinyin: "Nǐ shénme shíhou lái?", english: "When will you come?" } },
    { id: 44, chinese: "点", pinyin: "diǎn", english: "o'clock, point", example: { chinese: "现在三点半。", pinyin: "Xiànzài sān diǎn bàn.", english: "It's 3:30 now." } },
    { id: 45, chinese: "分钟", pinyin: "fēnzhōng", english: "minute", example: { chinese: "请等我五分钟。", pinyin: "Qǐng děng wǒ wǔ fēnzhōng.", english: "Please wait for me five minutes." } },
    { id: 46, chinese: "早上", pinyin: "zǎoshang", english: "morning", example: { chinese: "早上好！", pinyin: "Zǎoshang hǎo!", english: "Good morning!" } },
    { id: 47, chinese: "上午", pinyin: "shàngwǔ", english: "morning (before noon)", example: { chinese: "我上午有课。", pinyin: "Wǒ shàngwǔ yǒu kè.", english: "I have class in the morning." } },
    { id: 48, chinese: "中午", pinyin: "zhōngwǔ", english: "noon", example: { chinese: "我们中午一起吃饭吧。", pinyin: "Wǒmen zhōngwǔ yìqǐ chīfàn ba.", english: "Let's eat together at noon." } },
    { id: 49, chinese: "下午", pinyin: "xiàwǔ", english: "afternoon", example: { chinese: "下午我要去买东西。", pinyin: "Xiàwǔ wǒ yào qù mǎi dōngxi.", english: "I'm going shopping this afternoon." } },
    { id: 50, chinese: "晚上", pinyin: "wǎnshang", english: "evening, night", example: { chinese: "晚上我看电视。", pinyin: "Wǎnshang wǒ kàn diànshì.", english: "I watch TV in the evening." } },
    { id: 51, chinese: "去年", pinyin: "qùnián", english: "last year", example: { chinese: "去年我去了中国。", pinyin: "Qùnián wǒ qù le Zhōngguó.", english: "I went to China last year." } },
    { id: 52, chinese: "今年", pinyin: "jīnnián", english: "this year", example: { chinese: "今年我二十五岁。", pinyin: "Jīnnián wǒ èrshíwǔ suì.", english: "I'm 25 years old this year." } },
    { id: 53, chinese: "明年", pinyin: "míngnián", english: "next year", example: { chinese: "明年我要去日本。", pinyin: "Míngnián wǒ yào qù Rìběn.", english: "I'm going to Japan next year." } },
    { id: 54, chinese: "以前", pinyin: "yǐqián", english: "before, ago", example: { chinese: "三年以前我住在上海。", pinyin: "Sān nián yǐqián wǒ zhù zài Shànghǎi.", english: "I lived in Shanghai three years ago." } },
    { id: 55, chinese: "以后", pinyin: "yǐhòu", english: "after, later", example: { chinese: "吃饭以后我去散步。", pinyin: "Chīfàn yǐhòu wǒ qù sànbù.", english: "I go for a walk after eating." } },
    { id: 56, chinese: "时间", pinyin: "shíjiān", english: "time", example: { chinese: "我没有时间。", pinyin: "Wǒ méiyǒu shíjiān.", english: "I don't have time." } },

    // Family
    { id: 57, chinese: "爸爸", pinyin: "bàba", english: "father, dad", example: { chinese: "我爸爸是医生。", pinyin: "Wǒ bàba shì yīshēng.", english: "My father is a doctor." } },
    { id: 58, chinese: "妈妈", pinyin: "māma", english: "mother, mom", example: { chinese: "妈妈在做饭。", pinyin: "Māma zài zuòfàn.", english: "Mom is cooking." } },
    { id: 59, chinese: "儿子", pinyin: "érzi", english: "son", example: { chinese: "他的儿子很聪明。", pinyin: "Tā de érzi hěn cōngming.", english: "His son is very smart." } },
    { id: 60, chinese: "女儿", pinyin: "nǚér", english: "daughter", example: { chinese: "她的女儿今年五岁。", pinyin: "Tā de nǚér jīnnián wǔ suì.", english: "Her daughter is five years old this year." } },
    { id: 61, chinese: "哥哥", pinyin: "gēge", english: "older brother", example: { chinese: "我哥哥在北京工作。", pinyin: "Wǒ gēge zài Běijīng gōngzuò.", english: "My older brother works in Beijing." } },
    { id: 62, chinese: "姐姐", pinyin: "jiějie", english: "older sister", example: { chinese: "姐姐比我大三岁。", pinyin: "Jiějie bǐ wǒ dà sān suì.", english: "My older sister is three years older than me." } },
    { id: 63, chinese: "弟弟", pinyin: "dìdi", english: "younger brother", example: { chinese: "我弟弟还在上学。", pinyin: "Wǒ dìdi hái zài shàngxué.", english: "My younger brother is still in school." } },
    { id: 64, chinese: "妹妹", pinyin: "mèimei", english: "younger sister", example: { chinese: "妹妹喜欢唱歌。", pinyin: "Mèimei xǐhuan chànggē.", english: "My younger sister likes to sing." } },
    { id: 65, chinese: "丈夫", pinyin: "zhàngfu", english: "husband", example: { chinese: "她丈夫是老师。", pinyin: "Tā zhàngfu shì lǎoshī.", english: "Her husband is a teacher." } },
    { id: 66, chinese: "妻子", pinyin: "qīzi", english: "wife", example: { chinese: "他和妻子住在上海。", pinyin: "Tā hé qīzi zhù zài Shànghǎi.", english: "He lives in Shanghai with his wife." } },
    { id: 67, chinese: "孩子", pinyin: "háizi", english: "child, children", example: { chinese: "孩子们在公园玩。", pinyin: "Háizimen zài gōngyuán wán.", english: "The children are playing in the park." } },
    { id: 68, chinese: "家", pinyin: "jiā", english: "home, family", example: { chinese: "我想回家。", pinyin: "Wǒ xiǎng huíjiā.", english: "I want to go home." } },
    { id: 69, chinese: "家人", pinyin: "jiārén", english: "family members", example: { chinese: "我很想念我的家人。", pinyin: "Wǒ hěn xiǎngniàn wǒ de jiārén.", english: "I miss my family very much." } },
    { id: 70, chinese: "朋友", pinyin: "péngyou", english: "friend", example: { chinese: "他是我最好的朋友。", pinyin: "Tā shì wǒ zuì hǎo de péngyou.", english: "He is my best friend." } },
    { id: 71, chinese: "同学", pinyin: "tóngxué", english: "classmate", example: { chinese: "我和同学一起学习。", pinyin: "Wǒ hé tóngxué yìqǐ xuéxí.", english: "I study together with my classmates." } },
    { id: 72, chinese: "老师", pinyin: "lǎoshī", english: "teacher", example: { chinese: "老师在教室里。", pinyin: "Lǎoshī zài jiàoshì lǐ.", english: "The teacher is in the classroom." } },
    { id: 73, chinese: "学生", pinyin: "xuésheng", english: "student", example: { chinese: "我是大学生。", pinyin: "Wǒ shì dàxuésheng.", english: "I am a college student." } },
    { id: 74, chinese: "先生", pinyin: "xiānsheng", english: "Mr., sir", example: { chinese: "王先生，您好！", pinyin: "Wáng xiānsheng, nín hǎo!", english: "Hello, Mr. Wang!" } },
    { id: 75, chinese: "小姐", pinyin: "xiǎojiě", english: "Miss, young lady", example: { chinese: "李小姐在吗？", pinyin: "Lǐ xiǎojiě zài ma?", english: "Is Miss Li there?" } },
    { id: 76, chinese: "人", pinyin: "rén", english: "person, people", example: { chinese: "这里有很多人。", pinyin: "Zhèlǐ yǒu hěn duō rén.", english: "There are many people here." } },
    { id: 77, chinese: "名字", pinyin: "míngzi", english: "name", example: { chinese: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", english: "What's your name?" } },

    // Places
    { id: 78, chinese: "中国", pinyin: "Zhōngguó", english: "China", example: { chinese: "我想去中国旅游。", pinyin: "Wǒ xiǎng qù Zhōngguó lǚyóu.", english: "I want to travel to China." } },
    { id: 79, chinese: "北京", pinyin: "Běijīng", english: "Beijing", example: { chinese: "北京是中国的首都。", pinyin: "Běijīng shì Zhōngguó de shǒudū.", english: "Beijing is the capital of China." } },
    { id: 80, chinese: "上海", pinyin: "Shànghǎi", english: "Shanghai", example: { chinese: "上海是一个大城市。", pinyin: "Shànghǎi shì yí ge dà chéngshì.", english: "Shanghai is a big city." } },
    { id: 81, chinese: "学校", pinyin: "xuéxiào", english: "school", example: { chinese: "学校在那边。", pinyin: "Xuéxiào zài nàbian.", english: "The school is over there." } },
    { id: 82, chinese: "医院", pinyin: "yīyuàn", english: "hospital", example: { chinese: "医院在哪儿？", pinyin: "Yīyuàn zài nǎr?", english: "Where is the hospital?" } },
    { id: 83, chinese: "商店", pinyin: "shāngdiàn", english: "store, shop", example: { chinese: "这个商店很大。", pinyin: "Zhège shāngdiàn hěn dà.", english: "This store is very big." } },
    { id: 84, chinese: "饭店", pinyin: "fàndiàn", english: "restaurant, hotel", example: { chinese: "那个饭店的菜很好吃。", pinyin: "Nàge fàndiàn de cài hěn hǎochī.", english: "That restaurant's food is delicious." } },
    { id: 85, chinese: "机场", pinyin: "jīchǎng", english: "airport", example: { chinese: "我去机场接朋友。", pinyin: "Wǒ qù jīchǎng jiē péngyou.", english: "I'm going to the airport to pick up a friend." } },
    { id: 86, chinese: "火车站", pinyin: "huǒchēzhàn", english: "train station", example: { chinese: "火车站离这儿很远。", pinyin: "Huǒchēzhàn lí zhèr hěn yuǎn.", english: "The train station is far from here." } },
    { id: 87, chinese: "房间", pinyin: "fángjiān", english: "room", example: { chinese: "我的房间很小。", pinyin: "Wǒ de fángjiān hěn xiǎo.", english: "My room is very small." } },
    { id: 88, chinese: "教室", pinyin: "jiàoshì", english: "classroom", example: { chinese: "教室里有三十个学生。", pinyin: "Jiàoshì lǐ yǒu sānshí ge xuésheng.", english: "There are 30 students in the classroom." } },
    { id: 89, chinese: "办公室", pinyin: "bàngōngshì", english: "office", example: { chinese: "请进我的办公室。", pinyin: "Qǐng jìn wǒ de bàngōngshì.", english: "Please come into my office." } },
    { id: 90, chinese: "银行", pinyin: "yínháng", english: "bank", example: { chinese: "银行几点开门？", pinyin: "Yínháng jǐ diǎn kāimén?", english: "What time does the bank open?" } },
    { id: 91, chinese: "超市", pinyin: "chāoshì", english: "supermarket", example: { chinese: "我去超市买东西。", pinyin: "Wǒ qù chāoshì mǎi dōngxi.", english: "I'm going to the supermarket to buy things." } },
    { id: 92, chinese: "公司", pinyin: "gōngsī", english: "company", example: { chinese: "他在一家大公司工作。", pinyin: "Tā zài yì jiā dà gōngsī gōngzuò.", english: "He works at a big company." } },
    { id: 93, chinese: "里", pinyin: "lǐ", english: "inside, in", example: { chinese: "书在书包里。", pinyin: "Shū zài shūbāo lǐ.", english: "The book is in the bag." } },
    { id: 94, chinese: "外", pinyin: "wài", english: "outside, out", example: { chinese: "外面下雨了。", pinyin: "Wàimiàn xiàyǔ le.", english: "It's raining outside." } },
    { id: 95, chinese: "上", pinyin: "shàng", english: "up, above, on", example: { chinese: "猫在桌子上。", pinyin: "Māo zài zhuōzi shàng.", english: "The cat is on the table." } },
    { id: 96, chinese: "下", pinyin: "xià", english: "down, below, under", example: { chinese: "鞋在床下。", pinyin: "Xié zài chuáng xià.", english: "The shoes are under the bed." } },
    { id: 97, chinese: "前", pinyin: "qián", english: "front, before", example: { chinese: "学校在前面。", pinyin: "Xuéxiào zài qiánmiàn.", english: "The school is in front." } },
    { id: 98, chinese: "后", pinyin: "hòu", english: "back, after, behind", example: { chinese: "银行在超市后面。", pinyin: "Yínháng zài chāoshì hòumiàn.", english: "The bank is behind the supermarket." } },
    { id: 99, chinese: "左", pinyin: "zuǒ", english: "left", example: { chinese: "往左走。", pinyin: "Wǎng zuǒ zǒu.", english: "Go left." } },
    { id: 100, chinese: "右", pinyin: "yòu", english: "right", example: { chinese: "银行在右边。", pinyin: "Yínháng zài yòubiān.", english: "The bank is on the right." } },
    { id: 101, chinese: "旁边", pinyin: "pángbiān", english: "beside, next to", example: { chinese: "他坐在我旁边。", pinyin: "Tā zuò zài wǒ pángbiān.", english: "He sits beside me." } },
    { id: 102, chinese: "对面", pinyin: "duìmiàn", english: "opposite, across", example: { chinese: "超市在银行对面。", pinyin: "Chāoshì zài yínháng duìmiàn.", english: "The supermarket is across from the bank." } },

    // Common Nouns
    { id: 103, chinese: "东西", pinyin: "dōngxi", english: "thing, stuff", example: { chinese: "你买了什么东西？", pinyin: "Nǐ mǎi le shénme dōngxi?", english: "What did you buy?" } },
    { id: 104, chinese: "水", pinyin: "shuǐ", english: "water", example: { chinese: "请给我一杯水。", pinyin: "Qǐng gěi wǒ yì bēi shuǐ.", english: "Please give me a glass of water." } },
    { id: 105, chinese: "茶", pinyin: "chá", english: "tea", example: { chinese: "你想喝茶吗？", pinyin: "Nǐ xiǎng hē chá ma?", english: "Would you like some tea?" } },
    { id: 106, chinese: "咖啡", pinyin: "kāfēi", english: "coffee", example: { chinese: "我每天喝咖啡。", pinyin: "Wǒ měitiān hē kāfēi.", english: "I drink coffee every day." } },
    { id: 107, chinese: "米饭", pinyin: "mǐfàn", english: "rice (cooked)", example: { chinese: "中国人喜欢吃米饭。", pinyin: "Zhōngguó rén xǐhuan chī mǐfàn.", english: "Chinese people like to eat rice." } },
    { id: 108, chinese: "面条", pinyin: "miàntiáo", english: "noodles", example: { chinese: "这碗面条很好吃。", pinyin: "Zhè wǎn miàntiáo hěn hǎochī.", english: "This bowl of noodles is delicious." } },
    { id: 109, chinese: "菜", pinyin: "cài", english: "vegetable, dish", example: { chinese: "今天的菜很好吃。", pinyin: "Jīntiān de cài hěn hǎochī.", english: "Today's dishes are delicious." } },
    { id: 110, chinese: "水果", pinyin: "shuǐguǒ", english: "fruit", example: { chinese: "多吃水果对身体好。", pinyin: "Duō chī shuǐguǒ duì shēntǐ hǎo.", english: "Eating more fruit is good for your health." } },
    { id: 111, chinese: "苹果", pinyin: "píngguǒ", english: "apple", example: { chinese: "我想吃一个苹果。", pinyin: "Wǒ xiǎng chī yí ge píngguǒ.", english: "I want to eat an apple." } },
    { id: 112, chinese: "肉", pinyin: "ròu", english: "meat", example: { chinese: "你吃肉吗？", pinyin: "Nǐ chī ròu ma?", english: "Do you eat meat?" } },
    { id: 113, chinese: "鱼", pinyin: "yú", english: "fish", example: { chinese: "这条鱼很新鲜。", pinyin: "Zhè tiáo yú hěn xīnxiān.", english: "This fish is very fresh." } },
    { id: 114, chinese: "鸡蛋", pinyin: "jīdàn", english: "egg", example: { chinese: "早餐我吃了两个鸡蛋。", pinyin: "Zǎocān wǒ chī le liǎng ge jīdàn.", english: "I ate two eggs for breakfast." } },
    { id: 115, chinese: "牛奶", pinyin: "niúnǎi", english: "milk", example: { chinese: "孩子每天喝牛奶。", pinyin: "Háizi měitiān hē niúnǎi.", english: "Children drink milk every day." } },
    { id: 116, chinese: "面包", pinyin: "miànbāo", english: "bread", example: { chinese: "我早上吃面包。", pinyin: "Wǒ zǎoshang chī miànbāo.", english: "I eat bread in the morning." } },
    { id: 117, chinese: "钱", pinyin: "qián", english: "money", example: { chinese: "我没带钱。", pinyin: "Wǒ méi dài qián.", english: "I didn't bring money." } },
    { id: 118, chinese: "块", pinyin: "kuài", english: "yuan (colloquial), piece", example: { chinese: "这个十块钱。", pinyin: "Zhège shí kuài qián.", english: "This costs ten yuan." } },
    { id: 119, chinese: "书", pinyin: "shū", english: "book", example: { chinese: "这本书很有意思。", pinyin: "Zhè běn shū hěn yǒu yìsi.", english: "This book is very interesting." } },
    { id: 120, chinese: "电脑", pinyin: "diànnǎo", english: "computer", example: { chinese: "我用电脑工作。", pinyin: "Wǒ yòng diànnǎo gōngzuò.", english: "I work on the computer." } },
    { id: 121, chinese: "手机", pinyin: "shǒujī", english: "mobile phone", example: { chinese: "你的手机号码是多少？", pinyin: "Nǐ de shǒujī hàomǎ shì duōshao?", english: "What's your phone number?" } },
    { id: 122, chinese: "电话", pinyin: "diànhuà", english: "telephone", example: { chinese: "我给你打电话。", pinyin: "Wǒ gěi nǐ dǎ diànhuà.", english: "I'll call you." } },
    { id: 123, chinese: "电视", pinyin: "diànshì", english: "television", example: { chinese: "晚上我看电视。", pinyin: "Wǎnshang wǒ kàn diànshì.", english: "I watch TV in the evening." } },
    { id: 124, chinese: "衣服", pinyin: "yīfu", english: "clothes", example: { chinese: "这件衣服很漂亮。", pinyin: "Zhè jiàn yīfu hěn piàoliang.", english: "This piece of clothing is beautiful." } },
    { id: 125, chinese: "桌子", pinyin: "zhuōzi", english: "table, desk", example: { chinese: "书在桌子上。", pinyin: "Shū zài zhuōzi shàng.", english: "The book is on the table." } },
    { id: 126, chinese: "椅子", pinyin: "yǐzi", english: "chair", example: { chinese: "请坐这把椅子。", pinyin: "Qǐng zuò zhè bǎ yǐzi.", english: "Please sit on this chair." } },
    { id: 127, chinese: "门", pinyin: "mén", english: "door, gate", example: { chinese: "请关门。", pinyin: "Qǐng guān mén.", english: "Please close the door." } },
    { id: 128, chinese: "车", pinyin: "chē", english: "car, vehicle", example: { chinese: "他有一辆新车。", pinyin: "Tā yǒu yí liàng xīn chē.", english: "He has a new car." } },
    { id: 129, chinese: "飞机", pinyin: "fēijī", english: "airplane", example: { chinese: "飞机几点起飞？", pinyin: "Fēijī jǐ diǎn qǐfēi?", english: "What time does the plane take off?" } },
    { id: 130, chinese: "火车", pinyin: "huǒchē", english: "train", example: { chinese: "我坐火车去上海。", pinyin: "Wǒ zuò huǒchē qù Shànghǎi.", english: "I take the train to Shanghai." } },
    { id: 131, chinese: "出租车", pinyin: "chūzūchē", english: "taxi", example: { chinese: "我们打出租车去吧。", pinyin: "Wǒmen dǎ chūzūchē qù ba.", english: "Let's take a taxi." } },
    { id: 132, chinese: "路", pinyin: "lù", english: "road, way", example: { chinese: "这条路很远。", pinyin: "Zhè tiáo lù hěn yuǎn.", english: "This road is very long." } },
    { id: 133, chinese: "天气", pinyin: "tiānqì", english: "weather", example: { chinese: "今天天气怎么样？", pinyin: "Jīntiān tiānqì zěnmeyàng?", english: "How's the weather today?" } },
    { id: 134, chinese: "雨", pinyin: "yǔ", english: "rain", example: { chinese: "外面下雨了。", pinyin: "Wàimiàn xiàyǔ le.", english: "It's raining outside." } },
    { id: 135, chinese: "雪", pinyin: "xuě", english: "snow", example: { chinese: "冬天常常下雪。", pinyin: "Dōngtiān chángcháng xiàxuě.", english: "It often snows in winter." } },
    { id: 136, chinese: "风", pinyin: "fēng", english: "wind", example: { chinese: "今天风很大。", pinyin: "Jīntiān fēng hěn dà.", english: "The wind is strong today." } },
    { id: 137, chinese: "猫", pinyin: "māo", english: "cat", example: { chinese: "我家有一只猫。", pinyin: "Wǒ jiā yǒu yì zhī māo.", english: "I have a cat at home." } },
    { id: 138, chinese: "狗", pinyin: "gǒu", english: "dog", example: { chinese: "他的狗很可爱。", pinyin: "Tā de gǒu hěn kěài.", english: "His dog is very cute." } },
    { id: 139, chinese: "药", pinyin: "yào", english: "medicine", example: { chinese: "你吃药了吗？", pinyin: "Nǐ chī yào le ma?", english: "Did you take the medicine?" } },
    { id: 140, chinese: "票", pinyin: "piào", english: "ticket", example: { chinese: "我买了两张票。", pinyin: "Wǒ mǎi le liǎng zhāng piào.", english: "I bought two tickets." } },
    { id: 141, chinese: "事", pinyin: "shì", english: "thing, matter", example: { chinese: "没事，别担心。", pinyin: "Méi shì, bié dānxīn.", english: "It's nothing, don't worry." } },
    { id: 142, chinese: "问题", pinyin: "wèntí", english: "question, problem", example: { chinese: "你有什么问题？", pinyin: "Nǐ yǒu shénme wèntí?", english: "Do you have any questions?" } },
    { id: 143, chinese: "工作", pinyin: "gōngzuò", english: "work, job", example: { chinese: "你的工作是什么？", pinyin: "Nǐ de gōngzuò shì shénme?", english: "What is your job?" } },
    { id: 144, chinese: "电影", pinyin: "diànyǐng", english: "movie, film", example: { chinese: "我们去看电影吧。", pinyin: "Wǒmen qù kàn diànyǐng ba.", english: "Let's go watch a movie." } },
    { id: 145, chinese: "音乐", pinyin: "yīnyuè", english: "music", example: { chinese: "我喜欢听音乐。", pinyin: "Wǒ xǐhuan tīng yīnyuè.", english: "I like listening to music." } },
    { id: 146, chinese: "运动", pinyin: "yùndòng", english: "sports, exercise", example: { chinese: "运动对身体好。", pinyin: "Yùndòng duì shēntǐ hǎo.", english: "Exercise is good for your health." } },
    { id: 147, chinese: "报纸", pinyin: "bàozhǐ", english: "newspaper", example: { chinese: "爷爷每天看报纸。", pinyin: "Yéye měitiān kàn bàozhǐ.", english: "Grandpa reads the newspaper every day." } },
    { id: 148, chinese: "字", pinyin: "zì", english: "character, word", example: { chinese: "这个字怎么写？", pinyin: "Zhège zì zěnme xiě?", english: "How do you write this character?" } },
    { id: 149, chinese: "汉字", pinyin: "hànzì", english: "Chinese character", example: { chinese: "汉字很难学。", pinyin: "Hànzì hěn nán xué.", english: "Chinese characters are difficult to learn." } },
    { id: 150, chinese: "中文", pinyin: "Zhōngwén", english: "Chinese (language)", example: { chinese: "我在学中文。", pinyin: "Wǒ zài xué Zhōngwén.", english: "I'm learning Chinese." } },
    { id: 151, chinese: "英文", pinyin: "Yīngwén", english: "English (language)", example: { chinese: "你会说英文吗？", pinyin: "Nǐ huì shuō Yīngwén ma?", english: "Can you speak English?" } },

    // Body Parts
    { id: 152, chinese: "头", pinyin: "tóu", english: "head", example: { chinese: "我头疼。", pinyin: "Wǒ tóu téng.", english: "I have a headache." } },
    { id: 153, chinese: "眼睛", pinyin: "yǎnjing", english: "eye", example: { chinese: "她的眼睛很大。", pinyin: "Tā de yǎnjing hěn dà.", english: "Her eyes are big." } },
    { id: 154, chinese: "耳朵", pinyin: "ěrduo", english: "ear", example: { chinese: "我耳朵不舒服。", pinyin: "Wǒ ěrduo bù shūfu.", english: "My ears are uncomfortable." } },
    { id: 155, chinese: "鼻子", pinyin: "bízi", english: "nose", example: { chinese: "他鼻子很高。", pinyin: "Tā bízi hěn gāo.", english: "He has a high nose." } },
    { id: 156, chinese: "嘴", pinyin: "zuǐ", english: "mouth", example: { chinese: "请张开嘴。", pinyin: "Qǐng zhāng kāi zuǐ.", english: "Please open your mouth." } },
    { id: 157, chinese: "手", pinyin: "shǒu", english: "hand", example: { chinese: "请洗手。", pinyin: "Qǐng xǐ shǒu.", english: "Please wash your hands." } },
    { id: 158, chinese: "脚", pinyin: "jiǎo", english: "foot", example: { chinese: "我的脚很累。", pinyin: "Wǒ de jiǎo hěn lèi.", english: "My feet are tired." } },
    { id: 159, chinese: "身体", pinyin: "shēntǐ", english: "body", example: { chinese: "你身体好吗？", pinyin: "Nǐ shēntǐ hǎo ma?", english: "Are you in good health?" } },

    // Verbs
    { id: 160, chinese: "是", pinyin: "shì", english: "to be", example: { chinese: "他是我的老师。", pinyin: "Tā shì wǒ de lǎoshī.", english: "He is my teacher." } },
    { id: 161, chinese: "有", pinyin: "yǒu", english: "to have, there is", example: { chinese: "我有一个问题。", pinyin: "Wǒ yǒu yí ge wèntí.", english: "I have a question." } },
    { id: 162, chinese: "没有", pinyin: "méiyǒu", english: "don't have, there isn't", example: { chinese: "我没有时间。", pinyin: "Wǒ méiyǒu shíjiān.", english: "I don't have time." } },
    { id: 163, chinese: "在", pinyin: "zài", english: "to be at, in", example: { chinese: "他在家吗？", pinyin: "Tā zài jiā ma?", english: "Is he at home?" } },
    { id: 164, chinese: "去", pinyin: "qù", english: "to go", example: { chinese: "你去哪儿？", pinyin: "Nǐ qù nǎr?", english: "Where are you going?" } },
    { id: 165, chinese: "来", pinyin: "lái", english: "to come", example: { chinese: "请来这里。", pinyin: "Qǐng lái zhèlǐ.", english: "Please come here." } },
    { id: 166, chinese: "回", pinyin: "huí", english: "to return", example: { chinese: "我想回家。", pinyin: "Wǒ xiǎng huíjiā.", english: "I want to go home." } },
    { id: 167, chinese: "到", pinyin: "dào", english: "to arrive, to", example: { chinese: "我到了。", pinyin: "Wǒ dào le.", english: "I've arrived." } },
    { id: 168, chinese: "走", pinyin: "zǒu", english: "to walk, to go", example: { chinese: "我们走吧。", pinyin: "Wǒmen zǒu ba.", english: "Let's go." } },
    { id: 169, chinese: "跑", pinyin: "pǎo", english: "to run", example: { chinese: "他跑得很快。", pinyin: "Tā pǎo de hěn kuài.", english: "He runs very fast." } },
    { id: 170, chinese: "坐", pinyin: "zuò", english: "to sit", example: { chinese: "请坐。", pinyin: "Qǐng zuò.", english: "Please sit down." } },
    { id: 171, chinese: "站", pinyin: "zhàn", english: "to stand", example: { chinese: "请站起来。", pinyin: "Qǐng zhàn qǐlai.", english: "Please stand up." } },
    { id: 172, chinese: "睡觉", pinyin: "shuìjiào", english: "to sleep", example: { chinese: "我每天十点睡觉。", pinyin: "Wǒ měitiān shí diǎn shuìjiào.", english: "I go to sleep at 10 every day." } },
    { id: 173, chinese: "起床", pinyin: "qǐchuáng", english: "to get up", example: { chinese: "我早上六点起床。", pinyin: "Wǒ zǎoshang liù diǎn qǐchuáng.", english: "I get up at 6 in the morning." } },
    { id: 174, chinese: "吃", pinyin: "chī", english: "to eat", example: { chinese: "你吃饭了吗？", pinyin: "Nǐ chīfàn le ma?", english: "Have you eaten?" } },
    { id: 175, chinese: "喝", pinyin: "hē", english: "to drink", example: { chinese: "你想喝什么？", pinyin: "Nǐ xiǎng hē shénme?", english: "What would you like to drink?" } },
    { id: 176, chinese: "看", pinyin: "kàn", english: "to look, to watch", example: { chinese: "我在看书。", pinyin: "Wǒ zài kànshū.", english: "I'm reading a book." } },
    { id: 177, chinese: "听", pinyin: "tīng", english: "to listen", example: { chinese: "请听我说。", pinyin: "Qǐng tīng wǒ shuō.", english: "Please listen to me." } },
    { id: 178, chinese: "说", pinyin: "shuō", english: "to speak, to say", example: { chinese: "你会说中文吗？", pinyin: "Nǐ huì shuō Zhōngwén ma?", english: "Can you speak Chinese?" } },
    { id: 179, chinese: "读", pinyin: "dú", english: "to read", example: { chinese: "请读这个句子。", pinyin: "Qǐng dú zhège jùzi.", english: "Please read this sentence." } },
    { id: 180, chinese: "写", pinyin: "xiě", english: "to write", example: { chinese: "请写你的名字。", pinyin: "Qǐng xiě nǐ de míngzi.", english: "Please write your name." } },
    { id: 181, chinese: "学习", pinyin: "xuéxí", english: "to study, to learn", example: { chinese: "我在学习中文。", pinyin: "Wǒ zài xuéxí Zhōngwén.", english: "I'm studying Chinese." } },
    { id: 182, chinese: "教", pinyin: "jiāo", english: "to teach", example: { chinese: "他教我中文。", pinyin: "Tā jiāo wǒ Zhōngwén.", english: "He teaches me Chinese." } },
    { id: 183, chinese: "做", pinyin: "zuò", english: "to do, to make", example: { chinese: "你在做什么？", pinyin: "Nǐ zài zuò shénme?", english: "What are you doing?" } },
    { id: 184, chinese: "买", pinyin: "mǎi", english: "to buy", example: { chinese: "我想买这个。", pinyin: "Wǒ xiǎng mǎi zhège.", english: "I want to buy this." } },
    { id: 185, chinese: "卖", pinyin: "mài", english: "to sell", example: { chinese: "这个商店卖什么？", pinyin: "Zhège shāngdiàn mài shénme?", english: "What does this store sell?" } },
    { id: 186, chinese: "给", pinyin: "gěi", english: "to give", example: { chinese: "请给我一杯水。", pinyin: "Qǐng gěi wǒ yì bēi shuǐ.", english: "Please give me a glass of water." } },
    { id: 187, chinese: "送", pinyin: "sòng", english: "to send, to give (gift)", example: { chinese: "我送你一本书。", pinyin: "Wǒ sòng nǐ yì běn shū.", english: "I'll give you a book as a gift." } },
    { id: 188, chinese: "找", pinyin: "zhǎo", english: "to look for", example: { chinese: "我在找我的手机。", pinyin: "Wǒ zài zhǎo wǒ de shǒujī.", english: "I'm looking for my phone." } },
    { id: 189, chinese: "用", pinyin: "yòng", english: "to use", example: { chinese: "你会用筷子吗？", pinyin: "Nǐ huì yòng kuàizi ma?", english: "Can you use chopsticks?" } },
    { id: 190, chinese: "穿", pinyin: "chuān", english: "to wear", example: { chinese: "今天很冷，多穿点。", pinyin: "Jīntiān hěn lěng, duō chuān diǎn.", english: "It's cold today, wear more." } },
    { id: 191, chinese: "想", pinyin: "xiǎng", english: "to think, to want", example: { chinese: "我想你了。", pinyin: "Wǒ xiǎng nǐ le.", english: "I miss you." } },
    { id: 192, chinese: "知道", pinyin: "zhīdào", english: "to know", example: { chinese: "我不知道。", pinyin: "Wǒ bù zhīdào.", english: "I don't know." } },
    { id: 193, chinese: "认识", pinyin: "rènshi", english: "to know (person)", example: { chinese: "很高兴认识你。", pinyin: "Hěn gāoxìng rènshi nǐ.", english: "Nice to meet you." } },
    { id: 194, chinese: "懂", pinyin: "dǒng", english: "to understand", example: { chinese: "你懂了吗？", pinyin: "Nǐ dǒng le ma?", english: "Do you understand?" } },
    { id: 195, chinese: "会", pinyin: "huì", english: "can, will", example: { chinese: "我会游泳。", pinyin: "Wǒ huì yóuyǒng.", english: "I can swim." } },
    { id: 196, chinese: "能", pinyin: "néng", english: "can, be able to", example: { chinese: "你能帮我吗？", pinyin: "Nǐ néng bāng wǒ ma?", english: "Can you help me?" } },
    { id: 197, chinese: "可以", pinyin: "kěyǐ", english: "can, may", example: { chinese: "我可以进来吗？", pinyin: "Wǒ kěyǐ jìnlái ma?", english: "May I come in?" } },
    { id: 198, chinese: "要", pinyin: "yào", english: "to want, will", example: { chinese: "我要一杯咖啡。", pinyin: "Wǒ yào yì bēi kāfēi.", english: "I want a cup of coffee." } },
    { id: 199, chinese: "应该", pinyin: "yīnggāi", english: "should", example: { chinese: "你应该早点睡觉。", pinyin: "Nǐ yīnggāi zǎo diǎn shuìjiào.", english: "You should go to bed earlier." } },
    { id: 200, chinese: "喜欢", pinyin: "xǐhuan", english: "to like", example: { chinese: "我喜欢中国菜。", pinyin: "Wǒ xǐhuan Zhōngguó cài.", english: "I like Chinese food." } },
    { id: 201, chinese: "爱", pinyin: "ài", english: "to love", example: { chinese: "我爱你。", pinyin: "Wǒ ài nǐ.", english: "I love you." } },
    { id: 202, chinese: "觉得", pinyin: "juéde", english: "to feel, to think", example: { chinese: "你觉得怎么样？", pinyin: "Nǐ juéde zěnmeyàng?", english: "What do you think?" } },
    { id: 203, chinese: "希望", pinyin: "xīwàng", english: "to hope", example: { chinese: "我希望明天不下雨。", pinyin: "Wǒ xīwàng míngtiān bú xiàyǔ.", english: "I hope it won't rain tomorrow." } },
    { id: 204, chinese: "帮助", pinyin: "bāngzhù", english: "to help", example: { chinese: "谢谢你帮助我。", pinyin: "Xièxie nǐ bāngzhù wǒ.", english: "Thank you for helping me." } },
    { id: 205, chinese: "等", pinyin: "děng", english: "to wait", example: { chinese: "请等一下。", pinyin: "Qǐng děng yíxià.", english: "Please wait a moment." } },
    { id: 206, chinese: "问", pinyin: "wèn", english: "to ask", example: { chinese: "我可以问你一个问题吗？", pinyin: "Wǒ kěyǐ wèn nǐ yí ge wèntí ma?", english: "May I ask you a question?" } },
    { id: 207, chinese: "回答", pinyin: "huídá", english: "to answer", example: { chinese: "请回答这个问题。", pinyin: "Qǐng huídá zhège wèntí.", english: "Please answer this question." } },
    { id: 208, chinese: "告诉", pinyin: "gàosu", english: "to tell", example: { chinese: "请告诉我你的名字。", pinyin: "Qǐng gàosu wǒ nǐ de míngzi.", english: "Please tell me your name." } },
    { id: 209, chinese: "叫", pinyin: "jiào", english: "to call, to be called", example: { chinese: "我叫小明。", pinyin: "Wǒ jiào Xiǎo Míng.", english: "My name is Xiao Ming." } },
    { id: 210, chinese: "打电话", pinyin: "dǎ diànhuà", english: "to make a phone call", example: { chinese: "我给你打电话。", pinyin: "Wǒ gěi nǐ dǎ diànhuà.", english: "I'll call you." } },
    { id: 211, chinese: "开", pinyin: "kāi", english: "to open, to turn on", example: { chinese: "请开门。", pinyin: "Qǐng kāi mén.", english: "Please open the door." } },
    { id: 212, chinese: "关", pinyin: "guān", english: "to close, to turn off", example: { chinese: "请关灯。", pinyin: "Qǐng guān dēng.", english: "Please turn off the light." } },
    { id: 213, chinese: "进", pinyin: "jìn", english: "to enter", example: { chinese: "请进。", pinyin: "Qǐng jìn.", english: "Please come in." } },
    { id: 214, chinese: "出", pinyin: "chū", english: "to exit, to go out", example: { chinese: "我们出去走走吧。", pinyin: "Wǒmen chūqù zǒuzou ba.", english: "Let's go out for a walk." } },
    { id: 215, chinese: "上", pinyin: "shàng", english: "to go up, to attend", example: { chinese: "我上班了。", pinyin: "Wǒ shàngbān le.", english: "I've gone to work." } },
    { id: 216, chinese: "下", pinyin: "xià", english: "to go down", example: { chinese: "我们下楼吧。", pinyin: "Wǒmen xià lóu ba.", english: "Let's go downstairs." } },
    { id: 217, chinese: "玩", pinyin: "wán", english: "to play", example: { chinese: "孩子们在玩游戏。", pinyin: "Háizimen zài wán yóuxì.", english: "The children are playing games." } },
    { id: 218, chinese: "唱歌", pinyin: "chànggē", english: "to sing", example: { chinese: "她唱歌唱得很好。", pinyin: "Tā chànggē chàng de hěn hǎo.", english: "She sings very well." } },
    { id: 219, chinese: "跳舞", pinyin: "tiàowǔ", english: "to dance", example: { chinese: "我喜欢跳舞。", pinyin: "Wǒ xǐhuan tiàowǔ.", english: "I like dancing." } },
    { id: 220, chinese: "游泳", pinyin: "yóuyǒng", english: "to swim", example: { chinese: "夏天我常常去游泳。", pinyin: "Xiàtiān wǒ chángcháng qù yóuyǒng.", english: "I often go swimming in summer." } },
    { id: 221, chinese: "踢足球", pinyin: "tī zúqiú", english: "to play soccer", example: { chinese: "他喜欢踢足球。", pinyin: "Tā xǐhuan tī zúqiú.", english: "He likes playing soccer." } },
    { id: 222, chinese: "打篮球", pinyin: "dǎ lánqiú", english: "to play basketball", example: { chinese: "我们去打篮球吧。", pinyin: "Wǒmen qù dǎ lánqiú ba.", english: "Let's go play basketball." } },
    { id: 223, chinese: "开始", pinyin: "kāishǐ", english: "to begin, to start", example: { chinese: "电影几点开始？", pinyin: "Diànyǐng jǐ diǎn kāishǐ?", english: "What time does the movie start?" } },
    { id: 224, chinese: "完成", pinyin: "wánchéng", english: "to complete, to finish", example: { chinese: "我完成了作业。", pinyin: "Wǒ wánchéng le zuòyè.", english: "I finished my homework." } },
    { id: 225, chinese: "休息", pinyin: "xiūxi", english: "to rest", example: { chinese: "你累了，休息一下吧。", pinyin: "Nǐ lèi le, xiūxi yíxià ba.", english: "You're tired, take a rest." } },
    { id: 226, chinese: "准备", pinyin: "zhǔnbèi", english: "to prepare", example: { chinese: "你准备好了吗？", pinyin: "Nǐ zhǔnbèi hǎo le ma?", english: "Are you ready?" } },
    { id: 227, chinese: "介绍", pinyin: "jièshào", english: "to introduce", example: { chinese: "让我介绍一下。", pinyin: "Ràng wǒ jièshào yíxià.", english: "Let me introduce." } },
    { id: 228, chinese: "生病", pinyin: "shēngbìng", english: "to get sick", example: { chinese: "他生病了。", pinyin: "Tā shēngbìng le.", english: "He is sick." } },
    { id: 229, chinese: "笑", pinyin: "xiào", english: "to laugh, to smile", example: { chinese: "她笑得很开心。", pinyin: "Tā xiào de hěn kāixīn.", english: "She laughed happily." } },
    { id: 230, chinese: "哭", pinyin: "kū", english: "to cry", example: { chinese: "小孩儿在哭。", pinyin: "Xiǎoháir zài kū.", english: "The child is crying." } },
    { id: 231, chinese: "住", pinyin: "zhù", english: "to live, to stay", example: { chinese: "你住在哪儿？", pinyin: "Nǐ zhù zài nǎr?", english: "Where do you live?" } },
    { id: 232, chinese: "洗", pinyin: "xǐ", english: "to wash", example: { chinese: "我要洗手。", pinyin: "Wǒ yào xǐ shǒu.", english: "I need to wash my hands." } },
    { id: 233, chinese: "见面", pinyin: "jiànmiàn", english: "to meet", example: { chinese: "明天我们在哪儿见面？", pinyin: "Míngtiān wǒmen zài nǎr jiànmiàn?", english: "Where shall we meet tomorrow?" } },
    { id: 234, chinese: "旅游", pinyin: "lǚyóu", english: "to travel", example: { chinese: "我喜欢旅游。", pinyin: "Wǒ xǐhuan lǚyóu.", english: "I like traveling." } },
    { id: 235, chinese: "上班", pinyin: "shàngbān", english: "to go to work", example: { chinese: "我每天八点上班。", pinyin: "Wǒ měitiān bā diǎn shàngbān.", english: "I go to work at 8 every day." } },
    { id: 236, chinese: "下班", pinyin: "xiàbān", english: "to get off work", example: { chinese: "你几点下班？", pinyin: "Nǐ jǐ diǎn xiàbān?", english: "What time do you get off work?" } },

    // Adjectives
    { id: 237, chinese: "好", pinyin: "hǎo", english: "good", example: { chinese: "这本书很好。", pinyin: "Zhè běn shū hěn hǎo.", english: "This book is very good." } },
    { id: 238, chinese: "坏", pinyin: "huài", english: "bad", example: { chinese: "这个手机坏了。", pinyin: "Zhège shǒujī huài le.", english: "This phone is broken." } },
    { id: 239, chinese: "大", pinyin: "dà", english: "big, large", example: { chinese: "这个房子很大。", pinyin: "Zhège fángzi hěn dà.", english: "This house is very big." } },
    { id: 240, chinese: "小", pinyin: "xiǎo", english: "small, little", example: { chinese: "这只狗很小。", pinyin: "Zhè zhī gǒu hěn xiǎo.", english: "This dog is very small." } },
    { id: 241, chinese: "多", pinyin: "duō", english: "many, much", example: { chinese: "这里人很多。", pinyin: "Zhèlǐ rén hěn duō.", english: "There are many people here." } },
    { id: 242, chinese: "少", pinyin: "shǎo", english: "few, little", example: { chinese: "今天学生很少。", pinyin: "Jīntiān xuésheng hěn shǎo.", english: "There are few students today." } },
    { id: 243, chinese: "高", pinyin: "gāo", english: "tall, high", example: { chinese: "他很高。", pinyin: "Tā hěn gāo.", english: "He is very tall." } },
    { id: 244, chinese: "矮", pinyin: "ǎi", english: "short (height)", example: { chinese: "这棵树很矮。", pinyin: "Zhè kē shù hěn ǎi.", english: "This tree is very short." } },
    { id: 245, chinese: "长", pinyin: "cháng", english: "long", example: { chinese: "这条路很长。", pinyin: "Zhè tiáo lù hěn cháng.", english: "This road is very long." } },
    { id: 246, chinese: "短", pinyin: "duǎn", english: "short (length)", example: { chinese: "她的头发很短。", pinyin: "Tā de tóufa hěn duǎn.", english: "Her hair is very short." } },
    { id: 247, chinese: "新", pinyin: "xīn", english: "new", example: { chinese: "这是我的新手机。", pinyin: "Zhè shì wǒ de xīn shǒujī.", english: "This is my new phone." } },
    { id: 248, chinese: "旧", pinyin: "jiù", english: "old (things)", example: { chinese: "这本书很旧了。", pinyin: "Zhè běn shū hěn jiù le.", english: "This book is very old." } },
    { id: 249, chinese: "老", pinyin: "lǎo", english: "old (age)", example: { chinese: "我爷爷很老了。", pinyin: "Wǒ yéye hěn lǎo le.", english: "My grandfather is very old." } },
    { id: 250, chinese: "年轻", pinyin: "niánqīng", english: "young", example: { chinese: "你看起来很年轻。", pinyin: "Nǐ kàn qǐlai hěn niánqīng.", english: "You look very young." } },
    { id: 251, chinese: "快", pinyin: "kuài", english: "fast, quick", example: { chinese: "他跑得很快。", pinyin: "Tā pǎo de hěn kuài.", english: "He runs very fast." } },
    { id: 252, chinese: "慢", pinyin: "màn", english: "slow", example: { chinese: "请说慢一点。", pinyin: "Qǐng shuō màn yìdiǎn.", english: "Please speak slower." } },
    { id: 253, chinese: "早", pinyin: "zǎo", english: "early", example: { chinese: "你来得很早。", pinyin: "Nǐ lái de hěn zǎo.", english: "You came very early." } },
    { id: 254, chinese: "晚", pinyin: "wǎn", english: "late", example: { chinese: "对不起，我来晚了。", pinyin: "Duìbuqǐ, wǒ lái wǎn le.", english: "Sorry, I'm late." } },
    { id: 255, chinese: "热", pinyin: "rè", english: "hot", example: { chinese: "今天很热。", pinyin: "Jīntiān hěn rè.", english: "It's very hot today." } },
    { id: 256, chinese: "冷", pinyin: "lěng", english: "cold", example: { chinese: "冬天很冷。", pinyin: "Dōngtiān hěn lěng.", english: "Winter is very cold." } },
    { id: 257, chinese: "暖和", pinyin: "nuǎnhuo", english: "warm", example: { chinese: "今天很暖和。", pinyin: "Jīntiān hěn nuǎnhuo.", english: "It's very warm today." } },
    { id: 258, chinese: "凉快", pinyin: "liángkuai", english: "cool", example: { chinese: "这里很凉快。", pinyin: "Zhèlǐ hěn liángkuai.", english: "It's very cool here." } },
    { id: 259, chinese: "漂亮", pinyin: "piàoliang", english: "beautiful, pretty", example: { chinese: "她很漂亮。", pinyin: "Tā hěn piàoliang.", english: "She is very beautiful." } },
    { id: 260, chinese: "帅", pinyin: "shuài", english: "handsome", example: { chinese: "他长得很帅。", pinyin: "Tā zhǎng de hěn shuài.", english: "He is very handsome." } },
    { id: 261, chinese: "难看", pinyin: "nánkàn", english: "ugly", example: { chinese: "这件衣服很难看。", pinyin: "Zhè jiàn yīfu hěn nánkàn.", english: "This piece of clothing is ugly." } },
    { id: 262, chinese: "高兴", pinyin: "gāoxìng", english: "happy", example: { chinese: "我很高兴见到你。", pinyin: "Wǒ hěn gāoxìng jiàndào nǐ.", english: "I'm happy to see you." } },
    { id: 263, chinese: "快乐", pinyin: "kuàilè", english: "happy, joyful", example: { chinese: "祝你生日快乐！", pinyin: "Zhù nǐ shēngrì kuàilè!", english: "Happy birthday to you!" } },
    { id: 264, chinese: "难过", pinyin: "nánguò", english: "sad", example: { chinese: "他很难过。", pinyin: "Tā hěn nánguò.", english: "He is very sad." } },
    { id: 265, chinese: "累", pinyin: "lèi", english: "tired", example: { chinese: "我今天很累。", pinyin: "Wǒ jīntiān hěn lèi.", english: "I'm very tired today." } },
    { id: 266, chinese: "饿", pinyin: "è", english: "hungry", example: { chinese: "我饿了。", pinyin: "Wǒ è le.", english: "I'm hungry." } },
    { id: 267, chinese: "渴", pinyin: "kě", english: "thirsty", example: { chinese: "我很渴。", pinyin: "Wǒ hěn kě.", english: "I'm very thirsty." } },
    { id: 268, chinese: "忙", pinyin: "máng", english: "busy", example: { chinese: "他最近很忙。", pinyin: "Tā zuìjìn hěn máng.", english: "He's been very busy lately." } },
    { id: 269, chinese: "贵", pinyin: "guì", english: "expensive", example: { chinese: "这个太贵了。", pinyin: "Zhège tài guì le.", english: "This is too expensive." } },
    { id: 270, chinese: "便宜", pinyin: "piányi", english: "cheap", example: { chinese: "这个很便宜。", pinyin: "Zhège hěn piányi.", english: "This is very cheap." } },
    { id: 271, chinese: "容易", pinyin: "róngyì", english: "easy", example: { chinese: "这个问题很容易。", pinyin: "Zhège wèntí hěn róngyì.", english: "This question is very easy." } },
    { id: 272, chinese: "难", pinyin: "nán", english: "difficult", example: { chinese: "中文很难学。", pinyin: "Zhōngwén hěn nán xué.", english: "Chinese is difficult to learn." } },
    { id: 273, chinese: "对", pinyin: "duì", english: "correct, right", example: { chinese: "你说得对。", pinyin: "Nǐ shuō de duì.", english: "You're right." } },
    { id: 274, chinese: "错", pinyin: "cuò", english: "wrong", example: { chinese: "这个答案错了。", pinyin: "Zhège dá'àn cuò le.", english: "This answer is wrong." } },
    { id: 275, chinese: "近", pinyin: "jìn", english: "near", example: { chinese: "学校离这儿很近。", pinyin: "Xuéxiào lí zhèr hěn jìn.", english: "The school is near here." } },
    { id: 276, chinese: "远", pinyin: "yuǎn", english: "far", example: { chinese: "机场很远。", pinyin: "Jīchǎng hěn yuǎn.", english: "The airport is far." } },
    { id: 277, chinese: "重要", pinyin: "zhòngyào", english: "important", example: { chinese: "这件事很重要。", pinyin: "Zhè jiàn shì hěn zhòngyào.", english: "This matter is very important." } },
    { id: 278, chinese: "有意思", pinyin: "yǒu yìsi", english: "interesting", example: { chinese: "这个电影很有意思。", pinyin: "Zhège diànyǐng hěn yǒu yìsi.", english: "This movie is very interesting." } },
    { id: 279, chinese: "干净", pinyin: "gānjìng", english: "clean", example: { chinese: "这个房间很干净。", pinyin: "Zhège fángjiān hěn gānjìng.", english: "This room is very clean." } },
    { id: 280, chinese: "安静", pinyin: "ānjìng", english: "quiet", example: { chinese: "图书馆很安静。", pinyin: "Túshūguǎn hěn ānjìng.", english: "The library is very quiet." } },
    { id: 281, chinese: "聪明", pinyin: "cōngming", english: "smart, clever", example: { chinese: "这个孩子很聪明。", pinyin: "Zhège háizi hěn cōngming.", english: "This child is very smart." } },
    { id: 282, chinese: "健康", pinyin: "jiànkāng", english: "healthy", example: { chinese: "祝你身体健康！", pinyin: "Zhù nǐ shēntǐ jiànkāng!", english: "Wish you good health!" } },
    { id: 283, chinese: "舒服", pinyin: "shūfu", english: "comfortable", example: { chinese: "这张床很舒服。", pinyin: "Zhè zhāng chuáng hěn shūfu.", english: "This bed is very comfortable." } },
    { id: 284, chinese: "红", pinyin: "hóng", english: "red", example: { chinese: "她穿红色的衣服。", pinyin: "Tā chuān hóngsè de yīfu.", english: "She wears red clothes." } },
    { id: 285, chinese: "黄", pinyin: "huáng", english: "yellow", example: { chinese: "这朵花是黄色的。", pinyin: "Zhè duǒ huā shì huángsè de.", english: "This flower is yellow." } },
    { id: 286, chinese: "蓝", pinyin: "lán", english: "blue", example: { chinese: "天空是蓝色的。", pinyin: "Tiānkōng shì lánsè de.", english: "The sky is blue." } },
    { id: 287, chinese: "绿", pinyin: "lǜ", english: "green", example: { chinese: "树叶是绿色的。", pinyin: "Shùyè shì lǜsè de.", english: "The leaves are green." } },
    { id: 288, chinese: "白", pinyin: "bái", english: "white", example: { chinese: "雪是白色的。", pinyin: "Xuě shì báisè de.", english: "Snow is white." } },
    { id: 289, chinese: "黑", pinyin: "hēi", english: "black", example: { chinese: "她的头发是黑色的。", pinyin: "Tā de tóufa shì hēisè de.", english: "Her hair is black." } },

    // Adverbs
    { id: 290, chinese: "很", pinyin: "hěn", english: "very" },
    { id: 291, chinese: "太", pinyin: "tài", english: "too (much)" },
    { id: 292, chinese: "非常", pinyin: "fēicháng", english: "very, extremely" },
    { id: 293, chinese: "真", pinyin: "zhēn", english: "really, truly" },
    { id: 294, chinese: "最", pinyin: "zuì", english: "most" },
    { id: 295, chinese: "更", pinyin: "gèng", english: "more, even more" },
    { id: 296, chinese: "比较", pinyin: "bǐjiào", english: "relatively, quite" },
    { id: 297, chinese: "也", pinyin: "yě", english: "also, too" },
    { id: 298, chinese: "都", pinyin: "dōu", english: "all, both" },
    { id: 299, chinese: "还", pinyin: "hái", english: "still, also" },
    { id: 300, chinese: "再", pinyin: "zài", english: "again" },
    { id: 301, chinese: "又", pinyin: "yòu", english: "again, also" },
    { id: 302, chinese: "就", pinyin: "jiù", english: "then, just" },
    { id: 303, chinese: "才", pinyin: "cái", english: "only then, just" },
    { id: 304, chinese: "不", pinyin: "bù", english: "not" },
    { id: 305, chinese: "没", pinyin: "méi", english: "not, have not" },
    { id: 306, chinese: "别", pinyin: "bié", english: "don't" },
    { id: 307, chinese: "已经", pinyin: "yǐjīng", english: "already" },
    { id: 308, chinese: "正在", pinyin: "zhèngzài", english: "in the process of" },
    { id: 309, chinese: "一起", pinyin: "yìqǐ", english: "together" },
    { id: 310, chinese: "一直", pinyin: "yìzhí", english: "always, continuously" },
    { id: 311, chinese: "常常", pinyin: "chángcháng", english: "often" },
    { id: 312, chinese: "有时候", pinyin: "yǒushíhou", english: "sometimes" },
    { id: 313, chinese: "从来", pinyin: "cónglái", english: "never (before)" },
    { id: 314, chinese: "一定", pinyin: "yídìng", english: "certainly, definitely" },
    { id: 315, chinese: "可能", pinyin: "kěnéng", english: "maybe, possibly" },
    { id: 316, chinese: "大概", pinyin: "dàgài", english: "probably, about" },
    { id: 317, chinese: "马上", pinyin: "mǎshàng", english: "immediately" },
    { id: 318, chinese: "刚才", pinyin: "gāngcái", english: "just now" },

    // Prepositions & Conjunctions
    { id: 319, chinese: "和", pinyin: "hé", english: "and, with" },
    { id: 320, chinese: "跟", pinyin: "gēn", english: "with, and" },
    { id: 321, chinese: "从", pinyin: "cóng", english: "from" },
    { id: 322, chinese: "往", pinyin: "wǎng", english: "towards" },
    { id: 323, chinese: "向", pinyin: "xiàng", english: "towards" },
    { id: 324, chinese: "离", pinyin: "lí", english: "from (distance)" },
    { id: 325, chinese: "对", pinyin: "duì", english: "to, towards" },
    { id: 326, chinese: "比", pinyin: "bǐ", english: "compared to" },
    { id: 327, chinese: "因为", pinyin: "yīnwèi", english: "because" },
    { id: 328, chinese: "所以", pinyin: "suǒyǐ", english: "so, therefore" },
    { id: 329, chinese: "如果", pinyin: "rúguǒ", english: "if" },
    { id: 330, chinese: "虽然", pinyin: "suīrán", english: "although" },
    { id: 331, chinese: "但是", pinyin: "dànshì", english: "but, however" },
    { id: 332, chinese: "或者", pinyin: "huòzhě", english: "or" },
    { id: 333, chinese: "还是", pinyin: "háishi", english: "or (in questions)" },

    // Measure Words
    { id: 334, chinese: "个", pinyin: "gè", english: "general measure word" },
    { id: 335, chinese: "本", pinyin: "běn", english: "MW for books" },
    { id: 336, chinese: "张", pinyin: "zhāng", english: "MW for flat objects" },
    { id: 337, chinese: "件", pinyin: "jiàn", english: "MW for clothes, matters" },
    { id: 338, chinese: "条", pinyin: "tiáo", english: "MW for long things" },
    { id: 339, chinese: "只", pinyin: "zhī", english: "MW for animals" },
    { id: 340, chinese: "杯", pinyin: "bēi", english: "MW for cups" },
    { id: 341, chinese: "瓶", pinyin: "píng", english: "MW for bottles" },
    { id: 342, chinese: "碗", pinyin: "wǎn", english: "MW for bowls" },
    { id: 343, chinese: "次", pinyin: "cì", english: "MW for times" },
    { id: 344, chinese: "岁", pinyin: "suì", english: "years old" },
    { id: 345, chinese: "层", pinyin: "céng", english: "MW for floors" },
    { id: 346, chinese: "些", pinyin: "xiē", english: "some, a few" },

    // Common Phrases & Expressions
    { id: 347, chinese: "你好", pinyin: "nǐ hǎo", english: "hello" },
    { id: 348, chinese: "谢谢", pinyin: "xièxie", english: "thank you" },
    { id: 349, chinese: "不客气", pinyin: "bú kèqi", english: "you're welcome" },
    { id: 350, chinese: "对不起", pinyin: "duìbuqǐ", english: "sorry" },
    { id: 351, chinese: "没关系", pinyin: "méi guānxi", english: "it doesn't matter" },
    { id: 352, chinese: "再见", pinyin: "zàijiàn", english: "goodbye" },
    { id: 353, chinese: "请", pinyin: "qǐng", english: "please" },
    { id: 354, chinese: "欢迎", pinyin: "huānyíng", english: "welcome" },
    { id: 355, chinese: "生日快乐", pinyin: "shēngrì kuàilè", english: "happy birthday" },
    { id: 356, chinese: "新年快乐", pinyin: "xīnnián kuàilè", english: "happy new year" },
    { id: 357, chinese: "恭喜", pinyin: "gōngxǐ", english: "congratulations" },
    { id: 358, chinese: "加油", pinyin: "jiāyóu", english: "come on, go for it" },

    // More Common Words
    { id: 359, chinese: "每", pinyin: "měi", english: "every, each" },
    { id: 360, chinese: "全", pinyin: "quán", english: "whole, entire" },
    { id: 361, chinese: "只", pinyin: "zhǐ", english: "only" },
    { id: 362, chinese: "其他", pinyin: "qítā", english: "other" },
    { id: 363, chinese: "别的", pinyin: "biéde", english: "other, else" },
    { id: 364, chinese: "为了", pinyin: "wèile", english: "in order to" },
    { id: 365, chinese: "关于", pinyin: "guānyú", english: "about, regarding" },
    { id: 366, chinese: "除了", pinyin: "chúle", english: "except, besides" },
    { id: 367, chinese: "根据", pinyin: "gēnjù", english: "according to" },
    { id: 368, chinese: "通过", pinyin: "tōngguò", english: "through, via" },
    { id: 369, chinese: "得", pinyin: "de/děi", english: "particle/must" },
    { id: 370, chinese: "地", pinyin: "de", english: "adverb particle" },
    { id: 371, chinese: "的", pinyin: "de", english: "possessive particle" },
    { id: 372, chinese: "了", pinyin: "le", english: "completion particle" },
    { id: 373, chinese: "过", pinyin: "guò", english: "experience particle" },
    { id: 374, chinese: "着", pinyin: "zhe", english: "continuous particle" },
    { id: 375, chinese: "吗", pinyin: "ma", english: "question particle" },
    { id: 376, chinese: "呢", pinyin: "ne", english: "modal particle" },
    { id: 377, chinese: "吧", pinyin: "ba", english: "suggestion particle" },
    { id: 378, chinese: "啊", pinyin: "a", english: "exclamation particle" },

    // Additional Important Words
    { id: 379, chinese: "地方", pinyin: "dìfang", english: "place" },
    { id: 380, chinese: "国家", pinyin: "guójiā", english: "country" },
    { id: 381, chinese: "世界", pinyin: "shìjiè", english: "world" },
    { id: 382, chinese: "城市", pinyin: "chéngshì", english: "city" },
    { id: 383, chinese: "环境", pinyin: "huánjìng", english: "environment" },
    { id: 384, chinese: "情况", pinyin: "qíngkuàng", english: "situation" },
    { id: 385, chinese: "方法", pinyin: "fāngfǎ", english: "method" },
    { id: 386, chinese: "结果", pinyin: "jiéguǒ", english: "result" },
    { id: 387, chinese: "原因", pinyin: "yuányīn", english: "reason, cause" },
    { id: 388, chinese: "目的", pinyin: "mùdì", english: "purpose" },
    { id: 389, chinese: "历史", pinyin: "lìshǐ", english: "history" },
    { id: 390, chinese: "文化", pinyin: "wénhuà", english: "culture" },
    { id: 391, chinese: "经济", pinyin: "jīngjì", english: "economy" },
    { id: 392, chinese: "社会", pinyin: "shèhuì", english: "society" },
    { id: 393, chinese: "科学", pinyin: "kēxué", english: "science" },
    { id: 394, chinese: "技术", pinyin: "jìshù", english: "technology" },
    { id: 395, chinese: "艺术", pinyin: "yìshù", english: "art" },
    { id: 396, chinese: "教育", pinyin: "jiàoyù", english: "education" },
    { id: 397, chinese: "网络", pinyin: "wǎngluò", english: "internet, network" },
    { id: 398, chinese: "信息", pinyin: "xìnxī", english: "information" },
    { id: 399, chinese: "数字", pinyin: "shùzì", english: "number, digit" },
    { id: 400, chinese: "照片", pinyin: "zhàopiàn", english: "photo" },
    { id: 401, chinese: "节目", pinyin: "jiémù", english: "program, show" },
    { id: 402, chinese: "比赛", pinyin: "bǐsài", english: "competition, match" },
    { id: 403, chinese: "活动", pinyin: "huódòng", english: "activity" },
    { id: 404, chinese: "会议", pinyin: "huìyì", english: "meeting" },
    { id: 405, chinese: "计划", pinyin: "jìhuà", english: "plan" },
    { id: 406, chinese: "决定", pinyin: "juédìng", english: "decision, to decide" },
    { id: 407, chinese: "选择", pinyin: "xuǎnzé", english: "choice, to choose" },
    { id: 408, chinese: "同意", pinyin: "tóngyì", english: "to agree" },
    { id: 409, chinese: "反对", pinyin: "fǎnduì", english: "to oppose" },
    { id: 410, chinese: "支持", pinyin: "zhīchí", english: "to support" },
    { id: 411, chinese: "相信", pinyin: "xiāngxìn", english: "to believe" },
    { id: 412, chinese: "发现", pinyin: "fāxiàn", english: "to discover" },
    { id: 413, chinese: "了解", pinyin: "liǎojiě", english: "to understand" },
    { id: 414, chinese: "解决", pinyin: "jiějué", english: "to solve" },
    { id: 415, chinese: "参加", pinyin: "cānjiā", english: "to participate" },
    { id: 416, chinese: "表示", pinyin: "biǎoshì", english: "to express" },
    { id: 417, chinese: "提供", pinyin: "tígōng", english: "to provide" },
    { id: 418, chinese: "保护", pinyin: "bǎohù", english: "to protect" },
    { id: 419, chinese: "发展", pinyin: "fāzhǎn", english: "to develop" },
    { id: 420, chinese: "改变", pinyin: "gǎibiàn", english: "to change" },
    { id: 421, chinese: "增加", pinyin: "zēngjiā", english: "to increase" },
    { id: 422, chinese: "减少", pinyin: "jiǎnshǎo", english: "to decrease" },
    { id: 423, chinese: "提高", pinyin: "tígāo", english: "to improve" },
    { id: 424, chinese: "降低", pinyin: "jiàngdī", english: "to lower" },
    { id: 425, chinese: "影响", pinyin: "yǐngxiǎng", english: "influence, to affect" },
    { id: 426, chinese: "注意", pinyin: "zhùyì", english: "to pay attention" },
    { id: 427, chinese: "记得", pinyin: "jìde", english: "to remember" },
    { id: 428, chinese: "忘记", pinyin: "wàngjì", english: "to forget" },
    { id: 429, chinese: "检查", pinyin: "jiǎnchá", english: "to check" },
    { id: 430, chinese: "练习", pinyin: "liànxí", english: "to practice" },
    { id: 431, chinese: "复习", pinyin: "fùxí", english: "to review" },
    { id: 432, chinese: "考试", pinyin: "kǎoshì", english: "exam, to take exam" },
    { id: 433, chinese: "毕业", pinyin: "bìyè", english: "to graduate" },
    { id: 434, chinese: "成功", pinyin: "chénggōng", english: "success, to succeed" },
    { id: 435, chinese: "失败", pinyin: "shībài", english: "failure, to fail" },
    { id: 436, chinese: "努力", pinyin: "nǔlì", english: "to work hard" },
    { id: 437, chinese: "坚持", pinyin: "jiānchí", english: "to persist" },
    { id: 438, chinese: "放弃", pinyin: "fàngqì", english: "to give up" },
    { id: 439, chinese: "接受", pinyin: "jiēshòu", english: "to accept" },
    { id: 440, chinese: "拒绝", pinyin: "jùjué", english: "to refuse" },
    { id: 441, chinese: "满意", pinyin: "mǎnyì", english: "satisfied" },
    { id: 442, chinese: "失望", pinyin: "shīwàng", english: "disappointed" },
    { id: 443, chinese: "担心", pinyin: "dānxīn", english: "worried" },
    { id: 444, chinese: "紧张", pinyin: "jǐnzhāng", english: "nervous" },
    { id: 445, chinese: "害怕", pinyin: "hàipà", english: "afraid" },
    { id: 446, chinese: "生气", pinyin: "shēngqì", english: "angry" },
    { id: 447, chinese: "着急", pinyin: "zháojí", english: "anxious" },
    { id: 448, chinese: "奇怪", pinyin: "qíguài", english: "strange" },
    { id: 449, chinese: "特别", pinyin: "tèbié", english: "special, especially" },
    { id: 450, chinese: "普通", pinyin: "pǔtōng", english: "ordinary, common" },
    { id: 451, chinese: "一般", pinyin: "yìbān", english: "general, usually" },
    { id: 452, chinese: "正常", pinyin: "zhèngcháng", english: "normal" },
    { id: 453, chinese: "简单", pinyin: "jiǎndān", english: "simple" },
    { id: 454, chinese: "复杂", pinyin: "fùzá", english: "complicated" },
    { id: 455, chinese: "清楚", pinyin: "qīngchu", english: "clear" },
    { id: 456, chinese: "认真", pinyin: "rènzhēn", english: "serious, careful" },
    { id: 457, chinese: "仔细", pinyin: "zǐxì", english: "careful, detailed" },
    { id: 458, chinese: "方便", pinyin: "fāngbiàn", english: "convenient" },
    { id: 459, chinese: "必须", pinyin: "bìxū", english: "must" },
    { id: 460, chinese: "需要", pinyin: "xūyào", english: "need" },
    { id: 461, chinese: "愿意", pinyin: "yuànyì", english: "willing" },
    { id: 462, chinese: "敢", pinyin: "gǎn", english: "dare" },
    { id: 463, chinese: "打算", pinyin: "dǎsuàn", english: "to plan" },
    { id: 464, chinese: "经常", pinyin: "jīngcháng", english: "often" },
    { id: 465, chinese: "偶尔", pinyin: "ǒuěr", english: "occasionally" },
    { id: 466, chinese: "总是", pinyin: "zǒngshì", english: "always" },
    { id: 467, chinese: "终于", pinyin: "zhōngyú", english: "finally" },
    { id: 468, chinese: "突然", pinyin: "tūrán", english: "suddenly" },
    { id: 469, chinese: "首先", pinyin: "shǒuxiān", english: "first of all" },
    { id: 470, chinese: "然后", pinyin: "ránhòu", english: "then, after that" },
    { id: 471, chinese: "最后", pinyin: "zuìhòu", english: "finally, at last" },
    { id: 472, chinese: "只要", pinyin: "zhǐyào", english: "as long as" },
    { id: 473, chinese: "即使", pinyin: "jíshǐ", english: "even if" },
    { id: 474, chinese: "不管", pinyin: "bùguǎn", english: "no matter" },
    { id: 475, chinese: "而且", pinyin: "érqiě", english: "moreover" },
    { id: 476, chinese: "不但", pinyin: "búdàn", english: "not only" },
    { id: 477, chinese: "而是", pinyin: "érshì", english: "but rather" },
    { id: 478, chinese: "无论", pinyin: "wúlùn", english: "regardless" },
    { id: 479, chinese: "否则", pinyin: "fǒuzé", english: "otherwise" },
    { id: 480, chinese: "作为", pinyin: "zuòwéi", english: "as, being" },
    { id: 481, chinese: "关系", pinyin: "guānxi", english: "relationship" },
    { id: 482, chinese: "机会", pinyin: "jīhuì", english: "opportunity" },
    { id: 483, chinese: "经验", pinyin: "jīngyàn", english: "experience" },
    { id: 484, chinese: "能力", pinyin: "nénglì", english: "ability" },
    { id: 485, chinese: "水平", pinyin: "shuǐpíng", english: "level" },
    { id: 486, chinese: "态度", pinyin: "tàidu", english: "attitude" },
    { id: 487, chinese: "意见", pinyin: "yìjiàn", english: "opinion" },
    { id: 488, chinese: "建议", pinyin: "jiànyì", english: "suggestion" },
    { id: 489, chinese: "办法", pinyin: "bànfǎ", english: "way, method" },
    { id: 490, chinese: "作用", pinyin: "zuòyòng", english: "function, effect" },
    { id: 491, chinese: "效果", pinyin: "xiàoguǒ", english: "effect, result" },
    { id: 492, chinese: "标准", pinyin: "biāozhǔn", english: "standard" },
    { id: 493, chinese: "条件", pinyin: "tiáojiàn", english: "condition" },
    { id: 494, chinese: "基础", pinyin: "jīchǔ", english: "foundation" },
    { id: 495, chinese: "内容", pinyin: "nèiróng", english: "content" },
    { id: 496, chinese: "形式", pinyin: "xíngshì", english: "form" },
    { id: 497, chinese: "过程", pinyin: "guòchéng", english: "process" },
    { id: 498, chinese: "范围", pinyin: "fànwéi", english: "scope, range" },
    { id: 499, chinese: "程度", pinyin: "chéngdù", english: "degree, extent" },
    { id: 500, chinese: "数量", pinyin: "shùliàng", english: "quantity" }
];

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = HSK_VOCABULARY;
}
